### ISSUE TITLE
I wanted to know if version 2.29 is actually version 4?

### ISSUE THREAD

**Issue by lexterror** [johanmattssonm/birdfont#100]
Hi, is version 2.29 actually version 4? If not is there anywhere I can get the AppImage for version 4?

Thank you!

**Comment by johanmattssonm** [comment]
Hi
Version 2.29 has some of the features from 4.x but not all of them. There is a Flatpak at https://birdfont.org/ if you want to run 4.x on Linux.

**Comment by lexterror** [comment]
Hi, will the future versions of 2.29 have the features of 4.x?

**Comment by johanmattssonm** [comment]
I release some features in the open source version and additional features
in the commercial versions.

>

**Comment by lexterror** [comment]
Thank you!
