### ISSUE TITLE
Monochrome fallback causing instant crash. Not importing colour SVGs

### ISSUE THREAD

**Issue by LewisShawBCG** [johanmattssonm/birdfont#107]
Whenever I click the "Create monochrome glyph as TTF fallback" button, the programme immediately crashes.

Additionally, when I am importing SVG files with colour, the colours are not showing in Birdfont.

I'm running 4.8.7 Plus on Mac (Big Sur)

Any help would be appreciated, I'm a new user :)

**Comment by johanmattssonm** [comment]
Thank you for the report, can you send me the .bf file for debugging
purposes? You can send it via email if you don't want to make it public.

**Comment by LewisShawBCG** [comment]
Here you go
*Lewis Shaw*
Director

Find Braincrack Games on *Facebook
<https://www.facebook.com/braincrackgames/> • Twitter
<https://twitter.com/BraincrackGames> **• Instagram
<https://www.instagram.com/braincrackgames> **• Website
<https://www.braincrackgames.com/> **• Kickstarter
<https://www.kickstarter.com/profile/braincrack-games>*

For invoicing and payment queries please email payments@braincrackgames.com

Braincrack Games Ltd. is registered in the UK, company no. 10250033, VAT
reg. 313 6138 31. Our company address: 47 Orchard Place, SO14 3BW, United
Kingdom.* Note: This address is for correspondence only – please confirm
destinations for parcels before sending.*

**Comment by johanmattssonm** [comment]
Hi. It looks like the font didn't make its way to the report.

**Comment by LewisShawBCG** [comment]
What does that mean?

**Comment by johanmattssonm** [comment]
It looks like the attachment has been removed from you message, please try to add the font to the report.

**Comment by johanmattssonm** [comment]
Hi. I think I have found the problem (or actuall several problems). Do you want to test a beta version?
