### ISSUE TITLE
Certain SVGs importing with strange distortions

### ISSUE THREAD

**Issue by edwinfinch** [johanmattssonm/birdfont#109]
Hi there,

First off, thank you for all of the effort you've put in to making BirdFont great. It's been perfect for my project.

I'm only running into one small issue. Some SVG files that I import, such as an outlined `0`, show [strange distortions](https://me.lazarus.watch/_resources/external/birdfont-curve-issue.jpg).

[Here is my SVG file.](https://me.lazarus.watch/_resources/external/cursed_0.svg)

The strange thing is that my SVG looks fine on my Mac in Preview, and on Chrome as well as Safari.

I see I can fix the points of the character manually through BirdFont, but is there something wrong with the way I'm exporting my SVG through Adobe Illustrator? 

Thank you very much!

**Comment by johanmattssonm** [comment]
Many thanks for the bug report. I have not seen this issue before and I will try to fix it. I will also send you an email with a copy that happens to work for me.

**Comment by johanmattssonm** [comment]
Which version of Mac OS are you running?

**Comment by edwinfinch** [comment]
Thanks for the quick reply, Johan.

I'm running macOS 10.15.7. I'm still to scared to update to macOS Big Slurp ;)

**Comment by johanmattssonm** [comment]
Thank you. I might (if everything works out well ) send you a beta version
with a fix tomorrow.

**Comment by edwinfinch** [comment]
No rush, I fixed each of the broken graphics in BirdFont already, but still happy to try a beta for you if you need some quick testing done.

**Comment by johanmattssonm** [comment]
👍

**Comment by johanmattssonm** [comment]
A version with the fix has been released.
