### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Hulenkius** [johanmattssonm/birdfont#110]
Q1:
In FontCreator, Glyphs, FontForge, etc., there is some way to make glyphs "thin" or "bold", which is very useful in narrow/wide font production. Is it possible to make this in Birdfont?
Furtherfore, would there be a mass-adjustment tool which apply adjustments or effects to large quantities of glyphs?

Q2:
Some of my Asian friends have difficulties in reading Engish. Could Birdfont have multilanguage UI?

**Comment by johanmattssonm** [comment]
A1:  There is a tool in the overview tab to make glyphs thicker but it doesn't work that well.
A2: I had translations before but there was no good way to keep it up to date, I know very few languages and all translations where incomplete. You might be able to us Google translate on the tools page:
https://birdfont.org/tools.php
