### ISSUE TITLE
My SVG crashes BirdFont 4.10.2

### ISSUE THREAD

**Issue by edwinfinch** [johanmattssonm/birdfont#111]
Hi Johan,

Thanks again for your quick fix with my earlier issue.

This one is different. I'm now experiencing an app hang with BirdFont when importing a specific SVG for my project. I can't get BirdFont to respond, and I end up having to force quit it completely. 

Here is the SVG file: https://io.lazarus.watch/_resources/img/other/birdfont/dots.svg 

I understand this SVG is quite complex with all of its little dots. I'm wondering if there's a way to fix this issue on my end, or is there anything I can do to help you get it working with BirdFont?

I am running macOS Cantina Band (10.15.7) on a 2018 MacBook Pro. 

Regards,
Edwin

**Comment by johanmattssonm** [comment]
Many thanks for the report. You have created a path with many more points than any thing else I have seed (so far). I will look at it and hopefully find some way to optimize Birdfont for this case.

**Comment by johanmattssonm** [comment]
This file might make the editing slow even if I find some optimizations, mainly because the inside of the circle contains many small points.

**Comment by johanmattssonm** [comment]
I am working on it.

**Comment by edwinfinch** [comment]
For me, slow is alright. All I do is import my assets in SVG, resize them to a max height or width of 56pt, and centre them.

I don't do much other work, because it's not needed for my purposes. So as long as those work, that's good enough for me.

**Comment by edwinfinch** [comment]
Hi Johan,

My business partner (who is the one that creates the SVGs for me) created this simplified piece of the above SVG with less paths:

https://io.lazarus.watch/_resources/img/other/birdfont/dots-quarter.svg 

I was able to get this SVG to import into BirdFont, after about 40s of waiting. BirdFont is a bit slow to modify it, but I was able to do what I needed with all four quarters.

Hope this helps you on your quest of optimising BirdFont.

**Comment by johanmattssonm** [comment]
Many thanks. I think it will work but it will take some time to implement.

**Comment by johanmattssonm** [comment]
I think I might have a solution. Do you want to test a beta?

**Comment by edwinfinch** [comment]
That's great! Sure, send it over :)

**Comment by johanmattssonm** [comment]
Good. I will send you an email.
