### ISSUE TITLE
Not all letters are showing

### ISSUE THREAD

**Issue by corvaz87** [johanmattssonm/birdfont#114]
I created some letters but not working, my grab:

![Untitled-1](https://user-images.githubusercontent.com/83120624/115957378-56389b00-a502-11eb-925c-045fa9639b8e.gif)

**Comment by johanmattssonm** [comment]
Thank you for the report. Please send me the .birdfont file. Email is OK if you don't want it to become public.

**Comment by corvaz87** [comment]
Ok!

**Comment by johanmattssonm** [comment]
Did you send the file? It did not arrive.

**Comment by corvaz87** [comment]
I try again...

**Comment by johanmattssonm** [comment]
Same problem. Please try johan.mattsson.m@gmail.com

**Comment by johanmattssonm** [comment]
I believe this issue has been fixed. The problem was spacing of the lower case letters.
