### ISSUE TITLE
Unable to import background images with certain file names

### ISSUE THREAD

**Issue by Panogen** [johanmattssonm/birdfont#117]
I am creating a typeface for Japanese, and it follows that my background images are named in Japanese to keep them in alphabetical order. However, Birdfont doesn't seem to be able to handle this. When I try to import the images, nothing happens. I have to rename them with the Latin alphabet in order for them to be imported properly. When using the Background Image tab, adding a file such as あ.png causes the name あ to appear in the image list, but the image not to be visible. If I instead rename it to a.png and import it, it will appear correctly.
![no image](https://user-images.githubusercontent.com/73259774/119743165-1be25680-be3e-11eb-983f-85315569a3ca.PNG)
![image_renamed](https://user-images.githubusercontent.com/73259774/119743164-1b49c000-be3e-11eb-9d7b-1164de8c0727.PNG)

Renaming over 80 files to their Romaji counterparts is a big hassle, and it puts them out of order, so it would be great if the issue could be resolved.

**Comment by johanmattssonm** [comment]
Thank you for the report I will try to reproduce this.

**Comment by johanmattssonm** [comment]
Are you using Windows 10?

**Comment by johanmattssonm** [comment]
Hello. I think I have a solution. Do you want to test a beta? If yes please send me your email address.
Cheers

**Comment by johanmattssonm** [comment]
It might take a long time to load fonts with many background images. I suggest that you remove the background images from the font after you traced your glyphs.

**Comment by Panogen** [comment]
I'm using Windows 10, you can email the beta to albycnoble@gmail.com
About it taking a long time to load, I don't think that's the issue because it is happening even when there are no other background images loaded yet.

**Comment by johanmattssonm** [comment]
This issue has been fixed in version 4.17.3.
