### ISSUE TITLE
some svgs are bugged when loading

### ISSUE THREAD

**Issue by Hydr4gyrum** [johanmattssonm/birdfont#119]
The attached svg saves properly. but when reopenning the font file, it appears bugged. Editing the control points will fix the bug.
Bug shown in the attached png.

![2](https://user-images.githubusercontent.com/33533145/127270259-3586919c-7bd6-47cf-b54d-836816ec84d5.png)
[rsvg.zip](https://github.com/johanmattssonm/birdfont/files/6890626/rsvg.zip)

**Comment by johanmattssonm** [comment]
Hi. I tried reproduce this but your letter did look as expected when I imported it. Are you using the latest version of Birdfont?

**Comment by Hydr4gyrum** [comment]
yes, I downloaded the program just a few days ago. The letter looks fine when imported. But after exiting and reopenning the program, the bug occurs.

**Comment by johanmattssonm** [comment]
Thank you for the clarification. A fix for this bug will be included in the next version.

**Comment by johanmattssonm** [comment]
A version with a fix has been released.
