### ISSUE TITLE
[Question] Does birdfont support variable fonts?

### ISSUE THREAD

**Issue by Hawmex** [johanmattssonm/birdfont#121]

**Comment by KrasnayaPloshchad** [comment]
With this support it’s also possible to create multiple font files per font weight, OpenType specification allows to produce an individual font file from a static font variation instance.

**Comment by johanmattssonm** [comment]
I have a beta with using the gvar table. Do you want to test it?

**Comment by johanmattssonm** [comment]
Support for variable fonts has been added in version 5.
