### ISSUE TITLE
Erratic behavior of Bezier handles when holding SHIFT key

### ISSUE THREAD

**Issue by Panogen** [johanmattssonm/birdfont#124]
When editing a glyph, I frequently use the SHIFT+drag function to edit the length of control point handles. Unfortunately, upon returning to Birdfont after a couple months of using a different vector program, I discovered that an issue that used to only happen when I had the grid shown(turning off the grid would solve the problem)—namely, the Bezier handles spazzing out when I dragged them—was now happening everywhere. Seeing as I updated the software when I came back, I assume that the issue, or at least its universality, is relatively new.

Notes:
- The issue seems to get solved temporarily if you double-click to add a point on the path, then remove that point. Strangely, creating a new path does not have the same effect.
- If the handles are working normally(that is, moving smoothly while holding SHIFT), they will be broken again upon moving any control point(even if it's on a different path).

Attached is a video example of this bug.

https://user-images.githubusercontent.com/73259774/134787550-72fc5e42-731f-45a1-b665-37cf96c76b49.mp4

**Comment by johanmattssonm** [comment]
Many thanks for a very good report. I will try to fix this.

**Comment by johanmattssonm** [comment]
Hello. I have not managed to reproduce this but I have not given up yet. Which version of Birdfont are you using? Can you email me the font? johan.mattsson.m@gmail.com is the address.

**Comment by Panogen** [comment]
Hi,
My copy of Birdfont is on version 4.19.5.
Here's the Birdfont file I was using, though the issue doesn't seem local to just one font: [https://github.com/Panogen/Hotoshi-Quielic/blob/main/Hotoshi%20Kaku%20Gothic/Regular%20300/Development/Hotoshi%20Kaku%20Gothic%20Regular.birdfont](url)\
Unfortunately, Gmail seems to be down at the moment so I can't send the file that way. If you still want it through email, I could try again tomorrow to send it.

**Comment by johanmattssonm** [comment]
Hi. I had some trouble reproducing the problem but I think I might have a solution. Do you want to test a beta?

**Comment by Panogen** [comment]
Sure, here's my email: albycnoble@gmail.com

**Comment by johanmattssonm** [comment]
This issue is (hopefully) fixed in 4.20.
