### ISSUE TITLE
not able to export edited NOTO

### ISSUE THREAD

**Issue by bisketashwin** [johanmattssonm/birdfont#125]
Not able to export edited veresion of NOTO Sans which is SIL Open Font License
![image](https://user-images.githubusercontent.com/5793396/137738333-4e04ac26-c634-4150-bc63-5095c10d800b.png)

**Comment by bisketashwin** [comment]
So it is not exportable?

**Comment by johanmattssonm** [comment]
Not that particular file but this is:
https://github.com/googlefonts/noto-fonts/blob/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf

**Comment by nicknameHector** [comment]
Hi @johanmattssonm, I just created my own font using the free version of Birdfont and I got exactly the same message when trying to export to ttf. Apparently it should be possible to export to ttf with the free version of Birdfont based on their website.
Is it normal to get this error in the lastest version (4.26.2-free) as of today?

**Comment by johanmattssonm** [comment]
Which font are you using. I guess it might be an issue with the licensing of the font. Please attach it here.
Cheers

**Comment by nicknameHector** [comment]
Thank you for the fast reply.
[myFonts.zip](https://github.com/johanmattssonm/birdfont/files/8316216/myFonts.zip)

**Comment by johanmattssonm** [comment]
Thank you. This font is not licensed under the SIL OFL. The copyright statement says:
Copyright (c) GE Aviation. 2007. All rights reserved.

**Comment by nicknameHector** [comment]
Thank you so, much, indeed, that copyright was removing the validity of the license (I was working on an already existing doc).
Opening a whole new document and copying the glyphs there one by one solved my problem.
Thank you for your help!
