### ISSUE TITLE
changes do not appear in exported font

### ISSUE THREAD

**Issue by SPARQLCRMSUPPE** [johanmattssonm/birdfont#126]
Hi and thanks for your amazing work!

For some reason, changes made in Birdfont sometimes do / sometimes don't seem to be contained in the exported files, do / do not appear when installed. I haven't been able to get my head around any kind of system to the whole problem...

Thanks in advance!

[sachsenspiegel.zip](https://github.com/johanmattssonm/birdfont/files/7514872/sachsenspiegel.zip)

**Comment by johanmattssonm** [comment]
Thank you for the report. What kind of changes should I try to do?

**Comment by SPARQLCRMSUPPE** [comment]
Thanks for the swift reply! The issue is that when I make edits in Birdfont and then export the changes, they don't allways  seem to be implemented in the exported .tff files (sometimes, yes – mostly, no). Is this something you've encountered before by any chance? Im using vers. 4.20.0 on Mac, by the way.

**Comment by johanmattssonm** [comment]
I have not heard about this before. Could it be some kind och caching issue in the programs you are using to view the fonts? Please send me example fonts with and without changes if you manaage to reproduce this.

**Comment by SPARQLCRMSUPPE** [comment]
I hope this helps: Screenshots of the characters as shown in the birdfont editor + of their (missing) rendition in pages for mac, alongside the .tff files.
Again, thanks for your help!

[20211111_troubleshooting_sachsenspiegel.zip](https://github.com/johanmattssonm/birdfont/files/7517570/20211111_troubleshooting_sachsenspiegel.zip)

**Comment by johanmattssonm** [comment]
Thank you. I think the problem has to do with caching but kerning needs to be explicitly enabled in some programs.

**Comment by SPARQLCRMSUPPE** [comment]
;) Yeah, that was the weird bit: sometimes the kerning edits showed, sometimes they didn't. This has got to be a cache and pages related issue, I agree. Thanks for your help!
