### ISSUE TITLE
Birdfont seemingly selecting a range, and pasting a glyph multiple times

### ISSUE THREAD

**Issue by Adrakaris** [johanmattssonm/birdfont#128]
I'm currently stuck where birdfont seemingly selects two glyphs with a single click
![image](https://user-images.githubusercontent.com/17861497/150516140-69371241-6381-43a1-a07f-c203e8d3dc26.png)
In that image, I just clicked on >, but it has highlighted M as well

Furthermore to that, whenever I try paste a glyph, it seems to do it multiple times, overwriting the next three (or more) glyphs
![image](https://user-images.githubusercontent.com/17861497/150516292-6561fa9a-1cee-4438-bdaa-7cc0813f9dfc.png)
There I have selected >, copied > and pasted at the same spot, you can see it's duplicated 4 times

I don't know if this is a feature or a bug, nor how I turned it off or on in the first place. 

(I'm using the plus version, if that helps)

Edit: This seems to only happen in the "All glyphs" tab

**Comment by johanmattssonm** [comment]
Thank you for the report, this looks like a bug. Which version are you using?

**Comment by johanmattssonm** [comment]
I think I have found a solution. Do you want to test a beta version? Which OS and OS version are you using?

**Comment by Adrakaris** [comment]
Sure, I'm happy to test a beta version. I'm on Windows 10.

**Comment by johanmattssonm** [comment]
Nice. I have sent you an email with the beta.

**Comment by Adrakaris** [comment]
The beta seems to fix the issue, thanks. I've also replied to your email.
