### ISSUE TITLE
Gilbert Color font shows up as black, no SVG or COLR versions.

### ISSUE THREAD

**Issue by tkafka** [johanmattssonm/birdfont#137]
Hello, I wanted to use BirdFont to add a few glyphs to Gilbert Color ([freely available from typewithpride](https://www.typewithpride.com/)), but after opening the `Gilbert-Color Bold Preview5.otf`, the glyphs show up as black, and no glyphs show up in SVG and COLR view. Am I doing it wrong?
I have the Plus package (I just downloaded it, didn't find a place to enter a license, is that right?).

![Screenshot 2022-08-17 at 8 57 57](https://user-images.githubusercontent.com/876717/185054982-0980e743-8e93-4fd4-8245-9b0aa4e8704d.png)
![Screenshot 2022-08-17 at 8 57 55](https://user-images.githubusercontent.com/876717/185054993-fd13b927-2356-445c-8ac2-3a60e489ac7e.png)
![Screenshot 2022-08-17 at 8 56 13](https://user-images.githubusercontent.com/876717/185054997-a1295526-7edc-41e8-aef6-bffde5ef0416.png)

**Comment by johanmattssonm** [comment]
Hi, I have not implemented a parser for the SVG table in TTF and OTF fonts but it sound like someting I should work on.

**Comment by johanmattssonm** [comment]
Thank you for the report. I have added an OpenType SVG parser. Do you wan't to test a beta?

https://birdfont.org/misc/pride/Gilbert-Color-Bold-Preview5.birdfont

**Comment by johanmattssonm** [comment]
This issue has been fixed in the latest version of Birdfont (4.31).

**Comment by mfru** [comment]
for completeness sake, parsing color glyphs is working (tested on Fedora 38 with Birdfont 5.8.0 (plus) Flatpak:

![image](https://github.com/johanmattssonm/birdfont/assets/13270192/6b1a423e-c064-4f9c-a647-091b15fccf28)

**Comment by johanmattssonm** [comment]
Hi
Is this still a problem? It looks like the svg glyphs show up in the latest sceeenshot.

**Comment by mfru** [comment]
Hi, sorry, I might have written that confusingly.
There is no problem with this issue! 

I felt that the issue was incomplete because the person back then didn't react anymore.

This is a screenshot of it working, for completeness sake :)
