### ISSUE TITLE
Bugs with Hexadecimal color code

### ISSUE THREAD

**Issue by memowaveB** [johanmattssonm/birdfont#138]
Hello, some fonts work well with Hexadecimal color code, some others really don't.
I noticed bugs when using fonts with the Hexadecimal color code, below :

#ffff00
#ff7400
#fc0000
#f00fff
#b00000
#008000
#0090ff
#0F30ff
#8050ff
#5f055f
#906000
#604000

The corresponding colors in Birdfonf :
![screenshots 1](https://user-images.githubusercontent.com/10242268/188604689-6ca85434-daa4-48f9-bb17-1b2243850f2f.png)

The corresponding output in Word with the OTF format :

![screenshots 2](https://user-images.githubusercontent.com/10242268/188604733-efb4a1b2-9226-4fac-9430-5fd4cebf7e19.png)

Please, can you fix this bug ?

**Comment by johanmattssonm** [comment]
Thank you for the report. I will look at it later today. Please send me the .birdfont file.

**Comment by memowaveB** [comment]
My .birdfont file in a zip :
[1d - color bugs with Hexadecimal.zip](https://github.com/johanmattssonm/birdfont/files/9499993/1d.-.color.bugs.with.Hexadecimal.zip)

**Comment by johanmattssonm** [comment]
Thank you! I think I might have found it. Do you want to test a beta?

**Comment by memowaveB** [comment]
Hello Johan,
Yes, I 'm interested to test a beta. Thank you.

**Comment by johanmattssonm** [comment]
Thank you. This issue has been fixed in the latest version.
