### ISSUE TITLE
SVG import transform data

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [johanmattssonm/birdfont#14]
The app crashes when trying to import SVG that has transform data, is there a way to better handle this in the app, ideally the app should use the transform data to position the SVG above the baseline. If you remove the 2 transform data the app places the SVG below the baseline.    
[U+FB50.svg.zip](https://github.com/johanmattssonm/birdfont/files/190424/U.FB50.svg.zip)

**Comment by johanmattssonm** [comment]
Thank you for the report and for attaching the SVG file. I will take a look at it.

**Comment by johanmattssonm** [comment]
A fix is available in the 2.x branch.
