### ISSUE TITLE
Use the WebKitGTK 4.1 API builds when available

### ISSUE THREAD

**Issue by bertogg** [johanmattssonm/birdfont#140]
WebKitGTK switched to soup3 a while ago while keeping the older soup2 build for compatibility.

For apps that don't use libsoup directly (and therefore don't need to port the code to the new soup API) the only change that's needed is using webkit2gtk-4.1 instead of webkit2gtk-4.0.

**Comment by johanmattssonm** [comment]
Thanks. I updated to 4.1 and things still works for me on Ubuntu.
