### ISSUE TITLE
Artifact showing on strokes at vertices.

### ISSUE THREAD

**Issue by DamiJegede** [johanmattssonm/birdfont#142]
Mac OS Ventura
Version 4.31.3

Artifact showing on vertices below. Artifacts also appear on exported fonts. The fonts are 8pt stroke widths.

<img width="1146" alt="Screenshot 2022-12-02 at 9 14 22 PM" src="https://user-images.githubusercontent.com/5141357/205425176-88c144f3-b5d2-479f-8404-cb9b2f8e541f.png">
<img width="759" alt="Screenshot 2022-12-02 at 9 17 27 PM" src="https://user-images.githubusercontent.com/5141357/205425246-e3b0b24b-71eb-4595-959b-bf251b1a0ee3.png">
<img width="1151" alt="Screenshot 2022-12-02 at 9 17 11 PM" src="https://user-images.githubusercontent.com/5141357/205425249-f275f322-f959-4dcd-890e-edd6cb222e9f.png">
<img width="932" alt="Screenshot 2022-12-02 at 9 17 43 PM" src="https://user-images.githubusercontent.com/5141357/205425253-b56472b6-686d-4a1a-b775-d4d22f4f19d5.png">

**Comment by johanmattssonm** [comment]
Thank you for the report. Please send me the font (in .bf format). It is ok to use email if you don't want it to become public.

**Comment by johanmattssonm** [comment]
I think I have a solution now. Sorry for the delay. I will send you a version to test. Cheers!

**Comment by DamiJegede** [comment]
Received! Yeah! Works great! Thanks a million!
