### ISSUE TITLE
Unable to Export font created in v3.x

### ISSUE THREAD

**Issue by digitalchet** [johanmattssonm/birdfont#148]
I recently updated my BirdFont from v3.x to the latest version 5.0.8 and I am unable to export the fonts I created in v3.x. For both installs I selected to use the SIL Open Font License option as I'm still learning the app and testing the fonts, but after opening files edited in the earlier version and attempting to export, the message "**This font is not under the SIL Open Font License, you need the commercial version of BirdFont.**"
As a result, I can't test or use the font file. I am currently only attempting to export the TTF files.
Is there a way to set the file to fall under SILOFL?

Many thanks in advance for your help.

**Comment by johanmattssonm** [comment]
Please send me the font. I will only use it for debugging purposes. Email is OK if you don't want to make your font public. Address: johan.mattsson.m@gmail.com

**Comment by johanmattssonm** [comment]
It looks like it was a license issue with this font. Fixed.
