### ISSUE TITLE
Additional glyphs bricking font

### ISSUE THREAD

**Issue by visualkei72** [johanmattssonm/birdfont#149]
Hi! I just recently picked up this software on the recommendation of multiple mentions across forums. I'm running into an issue where if I define all the basic glyphs, there's no problem with the export. However if I start adding additional glyphs, i.e., brackets, reverse quotes, backslash, etc., the exported font won't display any of the glyphs that worked in the previous file.

Any ideas?

**Comment by johanmattssonm** [comment]
Sounds like a pretty serious bug. Please send me two example fonts in .birdfont format. One working and one not working. Email is OK if you don't want to make it public. Address: johan.mattsson.m@gmail.com

**Comment by visualkei72** [comment]
Shot you an e-mail, Johan.

**Comment by johanmattssonm** [comment]
👍

**Comment by visualkei72** [comment]
Thanks for sorting the issue out for me. Really appreciate the help!

**Comment by johanmattssonm** [comment]
This was a caching issue in Photoshop.
