### ISSUE TITLE
Sidebar not working

### ISSUE THREAD

**Issue by davidseegert** [johanmattssonm/birdfont#150]
First of all, thank you for all the time and effort you are putting into this! 

I've just read version five has variable fonts and this is awesome! Unfortunately, I wasn't able to try it out yet, because, as it seems, there is a bug making control items in the left sidebar unclickable. It seems like it is not working over the whole application, including settings, overview and the glyph-editor page. The rest of the user interface seems to work alright. I've encountered this behaviour using version: 5.0.20 on an m1 mac. Please let me know if I can support you with any more information and I will do my best to help you out.

**Comment by johanmattssonm** [comment]
Thank you for the report. I don't think I managed to reproduce this. See the attached video.

https://user-images.githubusercontent.com/350392/225143383-12d6ca2e-7478-401d-8df8-7fcbd92191af.mov

Is there something else I could try?

**Comment by johanmattssonm** [comment]
I think I found a way to reproduce this bug. Thank you for reporting it. The latest version (5.0.22) includes a fix for this problem.

**Comment by johanmattssonm** [comment]
Does it work for you as well?

**Comment by davidseegert** [comment]
Wow, thank you for your very quick response! It's fixed now!
