### ISSUE TITLE
Cannot launch Birdfont in Windows 10 [5.8.0 and prior]

### ISSUE THREAD

**Issue by Martyste** [johanmattssonm/birdfont#163]
2 years after I last worked on my personal font with this amazing app I went back to resume working only to find out my installation of Birdfont didn't launch anymore. I shrugged it off, expecting such errors from a PC-transferred program and instead installed 5.8.0 Free.

Unfortunately, i get the same problem: Birdfont appears in the Task Manager as a background process for about 5 seconds, using some CPU ressources, before vanishing, without leaving an error message or a crash log. I tried clearing the contents of Appdata/local/birdfont, to no avail.

I tested fresh installs of various versions from 4.0.0 up to now, with all the same outcome. Clearly there's an underlying issue with my installation of Windows but I can't find any way to diagnose the issue for now.

I'm open to suggestions to figure this issue out... they would be greatly appreciated.
Best Regards

**Comment by johanmattssonm** [comment]
Thank you for the report. I have not been able to reproduce this.

Please generate a log file. Here is how you do that.
Open the file C:\Users\USER\AppData\Local\birdfont\settings in notepad and make sure the file contains:
log "true" 
(not log "false")
Start the program and wait for it to crash.
Look in C:\Users\USER\AppData\Local\birdfont for a new logfile. Please add it here or email it to me. ( johan.mattsson.m@gmail.com )

Cheers
Johan

**Comment by Martyste** [comment]
Quite the embarassing twist, but Windows being Windows, you can shake it all you want, the best course of action is a **reboot.**
This is what fixed my problem, even tho I technically rebooted twice for it to actually work. Folks who run into this issue, make sure to try this first!
