### ISSUE TITLE
Unable to export SIL licensed font

### ISSUE THREAD

**Issue by rdelian** [johanmattssonm/birdfont#168]
I am unable to export a font with the SIL OPEN FONT LICENSE license 

It can be downloaded from this repo:
https://github.com/0xType/0xProto?tab=OFL-1.1-1-ov-file

**Comment by johanmattssonm** [comment]
Thanks. It looks like they forgot to specify the license in the font. Here is a fix: https://birdfont.org/misc/0xProto-Regular.birdfont
