### ISSUE TITLE
Birdfont UI looks blurry on Fedora 39 (maybe on every Wayland distro)

### ISSUE THREAD

**Issue by mfru** [johanmattssonm/birdfont#169]
This is not a critical bug, but my eyes hurt everytime I look at Birdfonts UI for longer than 10 minutes as the difference in sharpness between my other desktop apps and Birdfont on a scaled 4k display are quite strong.

I don't know if this is a Birdfont-specific bug or if it has to do with XWayland, which seems to lead to a lot of blurred apps (found while looking for `flatpak blurry apps wayland`)

Birdfont version: 6.2.1 (Plus)
OS: Fedora Linux 39 (Workstation Edition)
Windowing System: Wayland
Display resolution: 3840 x 2160 (16:9) scaled to 200%

As comparison I have another flatpak open "Webfont Kit Generator" which is as sharp as it should be.

![image](https://github.com/johanmattssonm/birdfont/assets/13270192/880b45ac-4860-449d-9d53-08e0af401d9f)

![image](https://github.com/johanmattssonm/birdfont/assets/13270192/6af25d1b-45b7-4a26-901d-79bda20a5f8a)

**Comment by johanmattssonm** [comment]
Thanks. I don't have a high resolution screen to test this on but my guess is that it is a bug (or missing feature) in Birdfont. Do you have the GDK_SCALE parameter set? Does this happen on other Linux distros as well? I will download Fedora to check this but I might need your help because I don't have the hardware.
Cheers

**Comment by johanmattssonm** [comment]
Hi. I think I might been able to reproduce and fix this on Ubuntu (also using Wayland). Do you want to test a beta?

**Comment by mfru** [comment]
Hi, I'll let you know about the GDK_SCALE parameter tomorrow once I am back at my workstation.

I'd love to test the beta version as well :)

**Comment by johanmattssonm** [comment]
Great! I will send you an email with the beta.

**Comment by johanmattssonm** [comment]
Email sent.

**Comment by mfru** [comment]
I can confirm your fix working, everything is crisp now, thank you!

![image](https://github.com/johanmattssonm/birdfont/assets/13270192/82cd6201-1a43-4b58-96e5-bf77608c5ded)

**Comment by johanmattssonm** [comment]
Thank you for the testing. I will release it immediately.
