### ISSUE TITLE
Export Glyph as SVG

### ISSUE THREAD

**Issue by zufuliu** [johanmattssonm/birdfont#17]
svg generated by "Export Glyph as SVG" contains the line
mlns="http://www.w3.org/2000/svg" 

it should be xmlns="http://www.w3.org/2000/svg" 

Birdfont version 2.15.6 Windows.

**Comment by johanmattssonm** [comment]
Thank you for the report. I will take a look at it.

**Comment by johanmattssonm** [comment]
A fix is available in the 2.x branch.
