### ISSUE TITLE
Contextual Ligatures - How to

### ISSUE THREAD

**Issue by dxps** [johanmattssonm/birdfont#175]
Hello @johanmattssonm & Birdfont community!

Just bought the Plus edition of Birdfont to support your efforts and extend my preferred monospaced font to add some ligatures.

I manage to create simple ligatures for common use cases such as double or triple equal:
![image](https://github.com/user-attachments/assets/e880d7d5-51ab-497b-ace9-b820f09f1407)

Now, I want to have something like Fira Code has with unlimited number of the same (equal or minus) character:
![image](https://github.com/user-attachments/assets/cd37c397-efd9-4f67-add2-66b838ba6a6e)

I've read the [Ligatures](https://birdfont.org/doku/doku.php/ligatures) tutorial, but I'm not sure yet how to do this.
Can you please provide an example or guidance on how to do it?

Thank you!

**Comment by johanmattssonm** [comment]
Thanks. I am not sure how to do that but manually creating something like
10 ligatures might be an option. Another option might be to set lsb and rsb
to zero in the equal sign.

**Comment by dxps** [comment]
Oh, speaking about rsb @johanmattssonm  ... maybe I missed the details, but how can I precisely set the rsb?

Concrete example:

| context | screenshot |
| --- | --- |
| To create the `==` ligature, I started with `=` whose width is 55. | ![image](https://github.com/user-attachments/assets/2f087246-528b-4f42-9530-2b6139b01aa2) |
| I guess more by change I managed to set the width to 110 for `==` | ![image](https://github.com/user-attachments/assets/f251face-0888-4c5f-9bbc-fc0ccade8c13) |
| But for the `===` ligature, how can I set it as 165? | ![image](https://github.com/user-attachments/assets/57316063-60b3-4961-ab28-e86fb42d91c5) |

Thanks.

**Comment by johanmattssonm** [comment]
You can set rsb if you right click on the tiny triangle at the top of the
line.

**Comment by dxps** [comment]
Oh, interesting! Appreciate the quick feedback! :pray: 

Last question on this topic: maybe I'm just picky and it doesn't matter, but how could I set it to have exactly 165? :blush: 

As shown below, by setting the rsb to `8.75`, the ruler shows `164.999`.
I tried setting it to `8.751`, but it uses only two decimals.

![image](https://github.com/user-attachments/assets/dac1182d-014b-4581-8b64-d23230bcf76e)

**Comment by johanmattssonm** [comment]
Rsb and lsb values are measured from the end of the shape to the end line.
You can delete the shape, set the size and put back the shape if you want
to set the width. You can also set that value in the overview tab without
deleting any shapes.

**Comment by dxps** [comment]
Nice!

The first option is indeed simple, but then after pasting the previously copied rectangles, I have to set again the x & y for all the rectangle. Otherwise - if you start it from scratch (by setting the width first) - it's very user friendly.

Therefore, for this particular case I'd like to try the second option, but I don't understand where to set it.

To me, the Overview tab is where all the symbols are shown.
Searching for the one I'm interested, I can only click on the (i) icon:
![image](https://github.com/user-attachments/assets/b2980549-ed30-40be-9a14-bca055fc4580)

**Comment by johanmattssonm** [comment]
Here is the button. See attached image:
[image: Skärmbild 2024-08-21 221019.png]

**Comment by dxps** [comment]
Unfortunately, that image is not included in the email nor this issue.

**Comment by johanmattssonm** [comment]
Thanks here is the image:
![Screenshot from 2024-08-22 10-41-32](https://github.com/user-attachments/assets/af72939c-df71-4496-8a08-8385b3eb159c)

**Comment by dxps** [comment]
Thanks Johan!

Now it's clear.

I still - sorry ... :blush:  - have one thing unclear: since the glyph width is 50.00 (left screenshot), why the width is 56.00 when I'm creating a new ligature (right screenshot), please :question: 

|(default?) glyph width | new ligature's glyph width |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/8e961787-e53c-406e-849e-dd5f0ef7e280) | ![image](https://github.com/user-attachments/assets/97247580-d3bd-40f2-be13-d411f10d1b67) |

**Comment by johanmattssonm** [comment]
This might be a bug but things work more or less if you set both lsb and the width. Here is a video. 
[Screencast from 2024-08-22 11-17-39.webm](https://github.com/user-attachments/assets/3a53a060-a8d0-490f-8ca3-3a997f5f652d)

**Comment by johanmattssonm** [comment]
5 + 55 = 60

**Comment by dxps** [comment]
Got it! Thanks a lot for the help! :pray:
