### ISSUE TITLE
'Filter Characters' Feature Always Removes 'Hyphen-Minus' Symbol (Unless U+2d Is Used)

### ISSUE THREAD

**Issue by GeorgeWilkins** [johanmattssonm/birdfont#178]
![image](https://github.com/user-attachments/assets/35d12e6a-475b-4e60-b58a-1df66f315361)

In the above image, if `U+2d` is omitted, the `-` (hyphen/minus) symbol will be removed from the font, despite it being included in the retention list. This occurs even if the 'Copy Letter' feature is used to obtain and paste the correct `-` character into this box (ensuring it's not one of the many variations).

However using the `U+2d` string instead results in the `-` being retained as expected.

I would speculate this is a result of a bug in the _range parsing_ not recognising the `-` character as a _literal_ when delimited by spaces:
> You can also use Unicode ranges like a-z

**Comment by johanmattssonm** [comment]
Thank you for the report. I will look at it immediately.

**Comment by johanmattssonm** [comment]
Hi. I think I have a solution. Do you want to test a beta? If yes, please send me an email, address johan.mattsson.m at gmail.com

**Comment by johanmattssonm** [comment]
I also need to know which OS and OS version you are using.
Have a nice Sunday.

**Comment by GeorgeWilkins** [comment]
Thank you @johanmattssonm. E-mail sent.

Windows 10.0.19045 Build 19045

**Comment by GeorgeWilkins** [comment]
Appears to be fixed with the provided _beta_ release. 👍

Many thanks for your quick response.

**Comment by johanmattssonm** [comment]
Thanks. I will release the new version later this week.
