### ISSUE TITLE
Can not find webkitgtk-3.0

### ISSUE THREAD

**Issue by feryardiant** [johanmattssonm/birdfont#2]
In Ubuntu 14.04 64bit, actualy you need `libwebkitgtk-3.0-dev` instead of `libwebkitgtk-dev` (Your [README](https://github.com/johanmattssonm/birdfont/blob/master/README#L23))

**Comment by johanmattssonm** [comment]
Thank you. The bug is fixed now.

**Comment by feryardiant** [comment]
I notice that I need to install `python-gtk2-dev` as well, since I purge `libwebkitgtk-dev`

**Comment by johanmattssonm** [comment]
I will add that as well but I can't figure out which package that needs it.

**Comment by feryardiant** [comment]
I don't think that's a good idea, simply because `python-gtk2-dev` and `libwebkitgtk-dev` needs almost same dependencies and you already using `libwebkitgtk-3.0-dev` instead and per my #3 I see a lot of deprecation warning, so I think removing all deprecation warning is your top priority.

**Comment by johanmattssonm** [comment]
Almost all warning messages belong to bugs in the Vala compiler and the Gee package. But it might be worth fixing the problems there.
