### ISSUE TITLE
build doesn't compile things in parallel

### ISSUE THREAD

**Issue by vapier** [johanmattssonm/birdfont#23]
it's pretty common nowadays for people have dual or quad (or more) cores in their system.  the current build script though only runs one program at a time which ends up taking much longer than it should :(.

considering the hand rolled build system that's in use today, i don't see a good way of adding this in.

maybe the `build.py` could import the `multiprocessing` module and create a pool of processes, then pass that pool into `process_tasks`, and `process_tasks` would use that pool to run `execute_task`.  to force a sync, the `Builder` class could yield a sentinel object that `process_tasks` would look for -- when it sees that, it'd drain the pool.  that way the `Builder` class could yield all the copies, sync, yield valac, sync, yield all the compile statements, sync, etc...

**Comment by johanmattssonm** [comment]
I believe python-doit does this and the build.py script is just a very simplified doit interpreter that I use in order to to avoid some bugs in doit. I need to do some testing before I continue but doit is in the gentoo repo.

**Comment by vapier** [comment]
sorry, i hadn't heard of python-doit before.  that seems to work, so i'm fine with that solution.  thanks for the info!
