### ISSUE TITLE
Can't type s, u, or x in "Name and description" fields

### ISSUE THREAD

**Issue by e-matteson** [johanmattssonm/birdfont#26]
This is strange. When I try to type lowercase `s`, `u`, or `x` into any of the text boxes in the "Name and description" tab, they don't appear. All other alphanumeric characters work, and capital `S`, `U`, and `X` work.

Using birdfont 2.16.4, on arch linux.

EDIT:
When I try to type `u`, I get the following warnings:

```
** (birdfont:14805): WARNING **: Path.vala:963: No points in path.

** (birdfont:14805): WARNING **: Path.vala:163: No point
```

When I try to type `s` or `x`, there is no output.

I think this has something to with the bezier tool, whose shortcuts are `s`, `u`, and `x`. Relatedly, the bezier tool has stopped working (even after closing and re-opening birdfont). When I try to draw a line using the bezier tool, I get the warning `** (birdfont:14805): WARNING **: GtkWindow.vala:740: Button already is down. 1`, and no line appears.

**Comment by johanmattssonm** [comment]
I believe this issue has been fixed in the latest version. Please give it a try.
