### ISSUE TITLE
Port to latest WebKit2

### ISSUE THREAD

**Issue by jbicha** [johanmattssonm/birdfont#27]
I see that you ported to WebKit2GTK but you're using an older version. The current version in Ubuntu is

libwebkit2gtk-4.0-dev
gir1.2-webkit2-4.0

I recommend you target xenial instead of trusty since webkit2gtk is better supported there.

**Comment by johanmattssonm** [comment]
I have switched back and forth because some of the rpm based distros have older versions of Webkit. I am not sure how this will look in the next version but I will try to fix it if 4.0 is the only option in xenial.

**Comment by jbicha** [comment]
I wouldn't say 4.0 is the only option in Xenial, however it's the only webkitgtk that gets [security updates](http://www.ubuntu.com/usn/usn-3079-1/).

**Comment by KAMiKAZOW** [comment]
Well, in your https://build.opensuse.org/package/show/home:johanmattssonm/birdfont repo currently nothing builds because of that ¯\_(ツ)_/¯

**Comment by johanmattssonm** [comment]
Thank you for the report. Birdfont 2.16.10 builds against webkit-4.0.

**Comment by KAMiKAZOW** [comment]
Can't the build system detect the WebKit version and target the right one? Should be handy for RHEL/CentOS users (although I don't know how many of them would like to use Birdfont).

PS: Your repo is missing Fedora 24.
