### ISSUE TITLE
Birdfont doesn't show in gnome-software app

### ISSUE THREAD

**Issue by jbicha** [johanmattssonm/birdfont#30]
Birdfont doesn't show in the gnome-software app used by many Linux distributions because its metadata license is set to GPL-3.0.

According to the [standard](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-metadata_license) it needs to use a "permissive" software license instead.

The appstream format has changed since you added the metadata file to your repository. Now might be a good time to check for other things that could be updated.

resources/linux/birdfont.appdata.xml

http://appstream.ubuntu.com/zesty/universe/issues/birdfont.html

**Comment by johanmattssonm** [comment]
I believe this issue has been fixed.
Cheers
