### ISSUE TITLE
Program is slow, laggy

### ISSUE THREAD

**Issue by ngdias** [johanmattssonm/birdfont#32]
I'm using Windows 7 and Birdfont v.2.17.1

Clicking is in general not very responsive. I feel a delay between clicking and seeing the result or the response of moving the mouse. This and the lack of other shortcut tricks makes the program feel very slow to use (and unproductive).

**Comment by blureshadow** [comment]
It's extremely slow.

**Comment by withour** [comment]
I experience same problem on Win 10 pro. It consumes a lot of cpu just when I start it, my laptop turn on its fans like when using real-time renderer in blender and the program is slow and laggy.

**Comment by jimbo1qaz** [comment]
Same here, scrolling around the settings list causes the CEF process to peg a CPU core.

**Comment by Strum355** [comment]
Linux mint here, high cpu usage when scrolling

**Comment by johanmattssonm** [comment]
Which tab are you scrolling in?

**Comment by Strum355** [comment]
'All Glyphs'. Makes scrolling to the bottom a pain :/ Would love to use this over font forge

**Comment by BitOfGold** [comment]
The program is so unresponsive I cannot use it. (4-5s from click to reaction)
Sorry, the UI and features looks so much better than font forge :(

**Comment by johanmattssonm** [comment]
Which tab has the five second delay?

**Comment by BitOfGold** [comment]
OK I reinstalled it and it is somewhat faster. Opening program: 9-10s. Opening font from click on icon to directory list: 3s. Changing directory: 2s. Resizing window: 1s. Maximizing to UHD: 0.5s. Opening glyphs, clicking on All Glyphs, 1-2s.
After opening a glyph, editing has no problems, it's fast and usable!
Directory and glyph listing is frustratingly slow.
I hope this helps!

**Comment by johanmattssonm** [comment]
Thank you for the clarification.

**Comment by yuigoto** [comment]
Last time I used BFont was quite a while ago, so I decided to check out the most recent commercial version.

But the same thing with @BitOfGold happens to me here: scrolling through the `Settings` and `All Glyphs` tabs is really painfully slow, but editing the glyph is smooth.

Using Win 10 Pro + 8G RAM, but running on a regular HDD.

**Comment by yuigoto** [comment]
From what I tested here, the larger the window size, the slower scrolling becomes. If I resize it like this here:

![scroll-faster](https://user-images.githubusercontent.com/346572/36065775-b684cb20-0e86-11e8-9f27-f996b76bb642.png)

Scrolling becomes a bit more bearable. 😛

If I resize it to fill my screen (2560x1080), then it becomes reeeeeeeeally slow.

**Comment by nblackburn** [comment]
Same for me, it looks great but is completely unusable for me.

**Comment by ChrisTucker2000** [comment]
Can confirm. It's horribly slow, to the point that it is honestly completely unusable. Several seconds to open the "Open font" tab, several seconds to switch to a different folder, several seconds to open the "Settings" tab, several minutes to scroll down, several minutes to open a font. It is unusable.

**Comment by SirWaddles** [comment]
I'm getting the same problem, there is not a single interaction that doesn't take forever. I'm using the 'plus' version.

**Comment by ChristineBoersen** [comment]
Every click, every item takes seconds, and the program pegs a core while idle most of the time. Unfortunately this makes the software entirely unusable

**Comment by johanmattssonm** [comment]
Which part of the program is laggy? Does this happen in all tabs?

**Comment by yuigoto** [comment]
Just as everyone told above, the whole program runs slowly, at least on Windows. It's worse the higher the resolution is.

I can run it fine on 640x480, windowed, but not full screen on 1920x1080, as menu scrolls really slow. :/

**Comment by nblackburn** [comment]
@johanmattssonm The entire thing sadly.

**Comment by JaneSmith** [comment]
I have to agree. I don't mean to cause any offense, but this is possibly the absolute worst performing software I've ever used in my life. I can't think of anything else that runs this slowly. It's just unusable.

**Comment by Strum355** [comment]
@yuigoto not just windows, same on Linux. It pegs a single core

**Comment by yuigoto** [comment]
Oh, I couldn't try it yet on Linux. Tried it on Win10 first, on my laptop, and thought that maybe it's because of the Intel video card. But on my main PC (using a Radeon R7 250), it's still slow, so prob. not video. :/

**Comment by johanmattssonm** [comment]
BirdFont have always been a bit slow on Windows because glib performs less well on this platform. I have not heard about any performance problems on Mac or Linux before but I will certainly try to reproduce this.

**Comment by Strum355** [comment]
i5 6500, 16gb ram, gtx1070 and has much lag on linux for me

**Comment by johanmattssonm** [comment]
Thank you for the extra info. Is it equally slow on other computers?

**Comment by Strum355** [comment]
On windows 10, same PC, its equally slow (to my memory, it might be faster or slower than on linux, but slow either way)

**Comment by johanmattssonm** [comment]
The next version of BirdFont should be much faster than the older ones. Here is the file:
https://birdfont.org/download/birdfont-3.8.12-free.exe

I have no been able to test this build thoroughly and I would appreciate if someone could tell me if it works or not.

Cheers
Johan

**Comment by nblackburn** [comment]
@johanmattssonm This is a huge improvement, well done.

**Comment by johanmattssonm** [comment]
Thank you for testing the app!

**Comment by Vampire** [comment]
From a very short test, this seems much better and acutally usable now. :-)

**Comment by johanmattssonm** [comment]
Thank you.

**Comment by yuigoto** [comment]
From what I tested, I do sense quite the improvement on UI fluidity, specially on the resolution I had most problems (2560x1080). 👍 

Waiting for the next release to update the commercial edition. 😄

**Comment by johanmattssonm** [comment]
The faster commercial version is now available from the website.
