### ISSUE TITLE
Needs better navigation tools

### ISSUE THREAD

**Issue by ngdias** [johanmattssonm/birdfont#35]
I'm using Windows 7 and Birdfont v.2.17.1

 The Unicode set with 24k characters is very hard to navigate. You could for example add an option to scroll to a specific character the user would indicate by the code number. Filtering subsets by category would also be useful.

PgUp and PgDn is not consistent and skips character lines. Can't be used to thoroughly scan every character.

You could also add a Favourite list or a list of currently working characters.

**Comment by johanmattssonm** [comment]
You can search for a character, by their Unicode value or by their name in the UCD (Unicode Character Database). Ctrl+F is the keybindng.
