### ISSUE TITLE
birdfont can't start because api-ms.win-shcore-scaling.dll is missing

### ISSUE THREAD

**Issue by kayazinc** [johanmattssonm/birdfont#38]
After installing birdfont version: 2.18.4 on windows 7 pc and click on the icon to start, it prompted "birdfont can't start because api-ms.win-shcore-scaling dll is missing".

Please advise me how to resolve the issue.  Thanks.

**Comment by johanmattssonm** [comment]
You will get this message if you are trying to use the BirdFont version for Windows 10 on an older installation of Windows, Look for the other binary on the website.
