### ISSUE TITLE
Can't start program, api-ms-win-shcore-scaling-l1-1-1.dll is missing

### ISSUE THREAD

**Issue by saucefrog** [johanmattssonm/birdfont#40]
(Windows 7, 64-bit)

Right after double-clicking the icon, an error message appears telling me the above mentioned dll is missing. When I look at all the DLLs in the program folder, it's indeed not there. You might want to add it to the installer package...

**Comment by johanmattssonm** [comment]
You are using the version for Windows 10 on an older installation of Windows. Try the other binary.
