### ISSUE TITLE
Background imgs stay loaded when starting a new font and cant close um. on win 10 64bit

### ISSUE THREAD

**Issue by gizzmo123456** [johanmattssonm/birdfont#42]
in the prv video (http://hub.amstrike.com/birdfontBug/Desktop%2005.08.2017%20-%2023.57.26.02.mp4) i noticed that the backgorund imgs stayed loaded when i started a new font and i couldent close them. this was the first time i notices this

**Comment by johanmattssonm** [comment]
This issue is fixed in the repo. The code will be included in the next release.

**Comment by gizzmo123456** [comment]
awsome, i will check it out in the next release, thank you!
