### ISSUE TITLE
Not working well with imported circular strokes.

### ISSUE THREAD

**Issue by blureshadow** [johanmattssonm/birdfont#45]
![image](https://cloud.githubusercontent.com/assets/22298459/26023719/61296fe2-37cb-11e7-94e7-318865088a9d.png)
![image](https://cloud.githubusercontent.com/assets/22298459/26023728/86b089c6-37cb-11e7-838d-7327c8b22623.png)
As seen in the above file, the software doesn't import correctly paths even if they're fills if they have a clipping mask over them.

**Comment by johanmattssonm** [comment]
Thank you for the report. Can you send me the SVG files for debugging?

**Comment by blureshadow** [comment]
[0.zip](https://github.com/johanmattssonm/birdfont/files/998563/0.zip)
Here's the 0

**Comment by blaaz15** [comment]
I have the same problem. I'm using Inkscape 0.92 to design and Birdfont 2.18.3.
![image](https://cloud.githubusercontent.com/assets/1312132/26157146/b735d9de-3b18-11e7-820b-9c04e751c9ef.png)
Design file: [circle_import_problem.zip](https://github.com/johanmattssonm/birdfont/files/1007945/circle_import_problem.zip)

**Comment by blureshadow** [comment]
Might it be a problem with the way birdfont handles importing? I think I read on the Illustrator import page that it tries to convert the svg into some other type of vector. It probably doesn't handle the curves very well.

**Comment by johanmattssonm** [comment]
I believe this problem has been fixed in the 3.x version of BirdFont.
