### ISSUE TITLE
Kerning not working with export.

### ISSUE THREAD

**Issue by eelkmann** [johanmattssonm/birdfont#46]
I am using version 2.17.1 on one machine and for testing tried version 2.18.2 on a second machine and I am getting the same issue on both. 

I have the glyphs I wanted put in and then used a kerning class to make sure they connected properly in the script type font I am working with.

In preview mode everything looks perfect as it should. As in attached preview image.
![preview](https://user-images.githubusercontent.com/29260139/26893732-cadb4108-4b81-11e7-927f-44fa71ecc600.PNG)
 
My problem is when I try to export it for use it doesn't seem to stick. When I look at the ttf file created with its preview it clearly shows the kerning is not correct and the r is disconnected as in attached brown image.
![brown](https://user-images.githubusercontent.com/29260139/26893787-f9fe1064-4b81-11e7-96a4-901f68125e9b.PNG)

any ideas?

**Comment by johanmattssonm** [comment]
Do you have a huge number of kerning pairs? I am working on a solution that will makes it possible to add many more kerning pairs to a font but it is not ready for release yet.

**Comment by eelkmann** [comment]
Johan,

It looks like I have maybe 50 pairs?

All I really need is for the lowercase r glyph to be offset -10 points against everything. I customized that particular glyph from the font but the new one does not connect where the old one did and needs to be kearned to the left at all times.

When I created the class it made what looks like 2 entries for each other letter as you can see in the attached image.

If that isn’t the best way to do it let me know.

Thanks,

Eric Elkmann

**Comment by johanmattssonm** [comment]
That should not exceed the limit can you send me the bf file for debugging? The image did not make it through github.

**Comment by johanmattssonm** [comment]
Which programs are you using to view the font? Kerning is turned off by default in Microsoft Word but it should work by default in Firefox and Chrome.

**Comment by eelkmann** [comment]
Johan,

Attached is the BF file I have been working with. I have only redone the r glyph, everything else is working. Have attached again the screenshots of the BF preview that looks correct and the exported ttf preview where the r is clearly disconnected again.

Thanks,

Eric Elkmann

**Comment by johanmattssonm** [comment]
Thank you. You need to e-mail it directly to me (johan.mattsson.m@gmail.com) since github does not pass on your attachments.

**Comment by eelkmann** [comment]
Johan,

I have tried it in word but the screenshot is from the default windows font viewer I guess? It is the preview that comes up when I click on the exported font with all the sample quick brown fox sentences on it.

Thanks,

Eric Elkmann

**Comment by johanmattssonm** [comment]
Thank you for the extra info, it could very likely be a problem with the font preview in Windows.

**Comment by eelkmann** [comment]
Johan,

That could be the problem. It would explain the strangeness of it working correctly in the preview for sure. Do you know how to make windows / word automatically use the kerning properly?

Thanks,

Eric Elkmann

**Comment by johanmattssonm** [comment]
The kerning works fine on my system except in the font preview, I am not sure if they haven't implemented kerning or if there is an issue with the TTF generation. I looks to me like you can avoid kerning at all if you move the left guide to the beginning of your letter.

**Comment by eelkmann** [comment]
Johan,

If that is the easiest way I would definitely like to do it that way instead of messing with the kerning which doesn’t seem to want to work by default on windows. Do I move the left guide in the glyph itself or somewhere else in the interface?

Thanks,

Eric Elkmann

**Comment by eelkmann** [comment]
Johan,

Never mind, I found the left guide. Thanks so much for your help!

I really appreciate it and the ones using this font will be very appreciative as well.

Have an awesome day!

Thanks,

Eric Elkmann

**Comment by johanmattssonm** [comment]
Thank you.
