### ISSUE TITLE
Probably a Windows 10 Issue

### ISSUE THREAD

**Issue by Heyalma** [johanmattssonm/birdfont#48]
My computer recently updated Window 10 and as soon as that happened commercial bird font stopped working for me. Unless, it's something else. But i can't say for sure. All i know is that i have not made any other changes other than the automatic update for Windows 10.

I click on Bird Font (2.18.4) like i usually do but it doesn't open. 

Again, this is a recent issue as of yesterday and today. 

Thanks so much and i hope you can help me figure out how to get into birdfont again.

**Comment by johanmattssonm** [comment]
Thank you for the report I have not seen this on my Windows 10 installation. Do you get any error messages?

**Comment by Heyalma** [comment]
I have attached a screenshot. It just does not open for me. I didn't have issues before until recently. 

![birdfont-issue-screenshot](https://user-images.githubusercontent.com/22901288/27496784-568b8118-580c-11e7-81b9-d1588901fd77.png)

**Comment by johanmattssonm** [comment]
I have not been able to reproduce this yet but I have released a new version (2.19.0). Do you find the same problem with this version?

**Comment by alexcirco** [comment]
For anyone having this issue on Win10. The program is opened but the window is out of desktop bounds.

FIX
shift+right click on birdfont on taskbar > select move and drag until a minimized window appear. Maximize it.

**Comment by johanmattssonm** [comment]
Thank you for the solution. I will try to reproduce this.
