### ISSUE TITLE
Ligature export on a Mac

### ISSUE THREAD

**Issue by mrandrey** [johanmattssonm/birdfont#51]
Hello,

I created a ligature to substitute two characters with better-looking spacing. It works lovely in the "Spacing" tab of Birdfont, but when I export the font as a TTF, it doesn't seem to get picked up. I looked in Typography and it looks like "Contextual ligatures" is checked. Am I missing something obvious here or is this not supported?

Thanks.

**Comment by mrandrey** [comment]
I just checked and Contextual Substitution seems to work, but not ligatures. I'm basically trying to make spacing look better between several consecurive letters like V and A. If I use the Substitution to replace "A V" to "AV" (closer aligned), then what about a word like "A V A" (spaces representing non-ligatured). "A V" gets replaced by "AV", but "V A" doesn't get replaced by "VA" because there's no "V A" anymore, just an "AV" and an "A". Does this make sense? It's difficult to describe this in perfectly ligatured font. I'm happy to try again if it doesn't make sense.

**Comment by johanmattssonm** [comment]
Thank you for the report.

Can you send me the bf file for testing?

A contextual substitution or a ligature can not at a later point be used as input in another substitution, this is a limitation in the TTF format.

**Comment by mrandrey** [comment]
Sure. Here's the .bf file and some screen shots demonstrating some issues.
The substitution rules are simple—you should be able to tell the from the screenshot. One adjusts spacing on A when preceded by V and the other on V when preceded by A. Another rule creates a custom double-A when there are two A's next to each other.

On the Spacing tab screenshot, I have a row of AVAVAVAV and AAAAAAAA, but they don't come out smoothly, as you can tell. Every third substitution seems to be off.

Thanks for looking into it. Great work on the program. It's really well thought through and a pleasure to use.

**Comment by mrandrey** [comment]
[AV-Example.bf.zip](https://github.com/johanmattssonm/birdfont/files/1218743/AV-Example.bf.zip)
<img width="866" alt="screen shot 2017-08-11 at 8 15 06 am" src="https://user-images.githubusercontent.com/444565/29226578-3b31be7c-7e6e-11e7-8a20-18d9b2dd36da.png">
<img width="795" alt="screen shot 2017-08-11 at 8 15 13 am" src="https://user-images.githubusercontent.com/444565/29226580-3be20a2a-7e6e-11e7-8944-871946ac65b8.png">
<img width="924" alt="screen shot 2017-08-11 at 8 15 31 am" src="https://user-images.githubusercontent.com/444565/29226579-3bbe407c-7e6e-11e7-8fd5-4f263f1730aa.png">
<img width="932" alt="screen shot 2017-08-11 at 8 15 42 am" src="https://user-images.githubusercontent.com/444565/29226582-3c01d0c6-7e6e-11e7-87fe-3f26f5e50be7.png">

**Comment by johanmattssonm** [comment]
Excellent, thank you.

You can't have - (hyphen) in the glyph name. I will change this in the future to make the name and the substitution strings intuitive or at least documented.

Cheers

[AV-Example.bf.zip](https://github.com/johanmattssonm/birdfont/files/1218864/AV-Example.bf.zip)

**Comment by mrandrey** [comment]
I just replaced the dash with an underscore and I'm experiencing the same issues. Also, the double-A example doesn't have any hyphens and is still problematic. Note the "AAAAAAAA" screenshot that should be a neat row of double-A's rather than interspersed of converted and not converted A's.

**Comment by johanmattssonm** [comment]
Thank you for the testing. It seems like a problem with the preview. I tried to export your font and the result looks fine in Inkscape. Please correct me if I am wrong? :-)

**Comment by mrandrey** [comment]
No problem. Thanks for being so responsive.
I exported your file as TTF. When installing it came up with an minor error (just FYI):
<img width="612" alt="screen shot 2017-08-11 at 12 30 31 pm" src="https://user-images.githubusercontent.com/444565/29234267-843b9066-7e91-11e7-9305-eb1ed23f1903.png">

Then when I select the font in the Notes program, it appears that the double-A seems to work fine (whereas it's problematic on BF's preview), but the A's don't seem to be converting at all (different behavior than BF preview where some of the A's didn't convert). Also, you'll notice that there's some issue with overlapping shapes subtracting shape instead of adding it.
<img width="671" alt="screen shot 2017-08-11 at 12 32 32 pm" src="https://user-images.githubusercontent.com/444565/29234281-a5c878b6-7e91-11e7-8490-7a9b00667e17.png">

**Comment by johanmattssonm** [comment]
Thank you. I believe the substitution has been fixed in version 2.19.2. Here is how the substitution looks in the kerning tab and inkscape:
![kerning 2017-08-13 23-36-39](https://user-images.githubusercontent.com/350392/29325611-a6b05352-81e8-11e7-8436-afb3ae22d603.png)

I have not yet figured out why Mac OS warns about the structure of the name table.

The overlapping issue is a bug in the rendering application. Some application assumes that the even-odd rules apply to font data in contrast to the curve orientation rules of the TTF format. You can get around this issue by merging all paths in your design (Command + M).

**Comment by mrandrey** [comment]
On your screenshots I'm only seeing A's or V's convert in the "AVAVAVA" and "VAVAVA". Shouldn't they both convert, so that in either case both A's and V's are narrow?

I downloaded the latest version and I'm experiencing what your screenshots demonstrate. Somehow if the "V" gets replaced by "V-narrow" in "AVAVAV", it no longer registers as as "V", so in "AVAVAV" only the V's get replaced instead of both A's and V's.

The "AA" replacement now works well. Thanks for fixing that.

**Comment by johanmattssonm** [comment]
A program that implements GSUB substitution support will do this:
The first two letter in the sequence VAVA is V and A, the program will find a mach and replace the middle character with the narrow and continue after the middle glyphs in the sequence which is VA. It is also a match in the substitution table and A will be substituted. The same thing happens if the sequence is AV, V will be substituted and the program will continue after the middle letters in the substitution.

I have found a bug related multiple letters in the replacement. You will need a fix for both V and A to be replaced. I am working on it.

Thank you for testing this.

**Comment by mrandrey** [comment]
Great. Thanks for working on it. I'm cheering you on :-)
