### ISSUE TITLE
Binary distribution violates license/OSI OSS definition

### ISSUE THREAD

**Issue by indrora** [johanmattssonm/birdfont#53]
Currently, BirdFont nags you if you got the "freeware" version, and does not allow you to use anything but the SIL license.

This violates the GPL if not in word but in spirit, and definitely violates the OSI's Open Source Definition ( https://opensource.org/osd ) part 6:

># 6. No Discrimination Against Fields of Endeavor
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

(note that the license here can also refer to restrictions the program has; There's funky rules at play here, tread carefully)

The dialog (nag screen) is explicitly called the `LicenseDialog`. https://github.com/johanmattssonm/birdfont/blob/73e1ecb8df7a3c09833fd9ec068ba2d9cb9d1946/libbirdfont/LicenseDialog.vala#L19

This is a restriction on endeavor (commercial use). It's being treated like an addendum to the GPL (and it's still nag screen). 

All this is triggered in the main window:

https://github.com/johanmattssonm/birdfont/blob/73e1ecb8df7a3c09833fd9ec068ba2d9cb9d1946/birdfont/GtkWindow.vala#L150

**Comment by indrora** [comment]
adding: The OSI FAQ is pretty clear about this: https://opensource.org/faq#commercial

>#Can Open Source software be used for commercial purposes?
>Absolutely. All Open Source software can be used for commercial purpose; the Open Source Definition guarantees this. You can even sell Open Source software.
>
>However, note that commercial is not the same as proprietary. If you receive software under an Open Source license, you can always use that software for commercial purposes, but that doesn't always mean you can place further restrictions on people who receive the software from you. In particular, copyleft-style Open Source licenses require that, in at least some cases, when you distribute the software, you must do so under the same license you received it under.

**Comment by johanmattssonm** [comment]
The commercial version is not released under the GNU GPL but it links with LGPL libraries.

**Comment by indrora** [comment]
That's all fine and allowed but the otherwise free variant is released under the terms of the GPL and therefore falls under these terms.

Unless no binary distributions produced via you are released under the GPL, which must be stated as such if this is the case, and which means that BirdFont cannot be considered free software (to my understanding) as the canonical binary distribution is non-free.

On September 17, 2017 6:53:43 AM MDT, Johan Mattsson <notifications@github.com> wrote:
>The commercial version is not released under the GNU GPL but it links
>with LGPL libraries.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/johanmattssonm/birdfont/issues/53#issuecomment-330041788

--
Morgan Gangwere • zaibatsutel.net 
Sent from a mobile device. May contain autocorrect. Processed in a facility that handles nuts. Less than 2% juice.

**Comment by indrora** [comment]
Bump: LGPL library (libbirdfont) restricts the freedom of users via `#ifdef` check. Versions distributed as open source should not restrict freedoms of users.

**Comment by johanmattssonm** [comment]
I don't think this is a problem. The sourcode version does not use this restriction.
