### ISSUE TITLE
Unnecessary nodes in generated fonts

### ISSUE THREAD

**Issue by carlenlund** [johanmattssonm/birdfont#56]
I've noticed Birdfont unnecessarily adds nodes to generated fonts. This should be fixed, since clean paths generally are preferred in professional environments.

[NodeTest.bf.zip](https://github.com/johanmattssonm/birdfont/files/1591898/NodeTest.bf.zip)

![birdfont-issue](https://user-images.githubusercontent.com/29961051/34420093-e3128c5a-ec07-11e7-8e0e-01b9380a9070.png)

**Comment by johanmattssonm** [comment]
Control points are added in order to always have a point on the curve extrema. Many rendering engines depend on those points to get the spacing right. It obviously not needed in the sample you provided – it is a bug.

**Comment by johanmattssonm** [comment]
Can you attach the shape for testing?

**Comment by johanmattssonm** [comment]
I have created a patch that is supposed to fix this issue but I still need a BF file for testing.

**Comment by carlenlund** [comment]
Nice to hear! Here's the file and the output:  [node-test.zip](https://github.com/johanmattssonm/birdfont/files/1593463/node-test.zip)

**Comment by johanmattssonm** [comment]
Thank you. It seems to work.
