### ISSUE TITLE
Use file extensions other than .bf

### ISSUE THREAD

**Issue by carlenlund** [johanmattssonm/birdfont#57]
This is a really minor issue, but it I think you should be able to use file extensions other than .bf for the font files. The extension probably shouldn't matter at all. Using either .bf and .birdfont could work too. (Also .bf is commonly used for Brainfuck programs, which makes GitHub think the font file is something else.)
Thanks!

**Comment by carlenlund** [comment]
To clarify why this is an issue, when I open Birdfont files with extensions other than .bf, I'm unable to show any of the glyphs. The glyph list view shows nothing.

**Comment by nblackburn** [comment]
Completely understand your point but i think this is more of an issue for GitHub to address rather than this project.

**Comment by carlenlund** [comment]
The point is that the file type should be determined the file contents, not the extension of the file. A lot of editors do this. Again, this is a minor issue.

**Comment by nblackburn** [comment]
Well this issue contains more than one point, the first being the one i responded to but the second seems justified.

**Comment by johanmattssonm** [comment]
The file default fie extension will be .birdfont in the next release.

**Comment by johanmattssonm** [comment]
This issue has been fixed in version 3.11.
