### ISSUE TITLE
BadAccess when running flatpak on openSUSE Linux

### ISSUE THREAD

**Issue by digulla** [johanmattssonm/birdfont#59]
When running

    flatpak run org.birdfont.BirdFont

I get

> (birdfont:2): Gdk-ERROR **: The program 'birdfont' received an X Window System error.
> This probably reflects a bug in the program.
> The error was 'BadAccess (attempt to access private resource denied)'.

**Comment by digulla** [comment]
Run with the option `--share=ipc`:

    flatpak run --share=ipc org.birdfont.BirdFont

**Comment by txirrindulari** [comment]
> Run with the option `--share=ipc`:
> 
> ```
> flatpak run --share=ipc org.birdfont.BirdFont
> ```

Thank you, it works now. I got this error with version 5.3.0 in Ubuntu 22.04
