### ISSUE TITLE
Exported font seems to have wrong ascent/descent

### ISSUE THREAD

**Issue by weeble** [johanmattssonm/birdfont#6]
When I export this font as ttf/mac ttf, it seems to get different values for the ascent and descent from what I'd expect. The main symptom is that when the font is used, while it sits correctly on the baseline with other text, selecting the text results in a large area selected above the font while below the selection does not extend to the bottom of the descenders.

Here's the letter "p" in the font. The visible horizontal lines, from top to bottom, are "top margin", "top", "height", "x-height", "baseline", "bottom" and "bottom margin". Both "bottom" and "bottom margin" fall at or below the tail of the "p".

![screen shot 2015-08-05 at 22 47 20](https://cloud.githubusercontent.com/assets/663664/9099440/91a5d4e0-3bc8-11e5-9591-837253c234d3.png)

Here's what it looks like when the font is exported as ttf:

<img width="512" alt="screen shot 2015-08-05 at 22 44 01" src="https://cloud.githubusercontent.com/assets/663664/9099484/ec1d4c64-3bc8-11e5-886e-6a807068da4d.png">

As you can see, when the text is selected, the selection does not extend all the way to the bottom of the "p", while it extends quite some distance over the top. When the font is used in other programs it sometimes gets cut off at the bottom.

Here's a complete bf file:

https://gist.github.com/weeble/068287e0bbad8dd9c66e

This doesn't seem to happen in every font. I think it might be related to font/horizontal/base_line being non-zero, but I haven't really done enough experiments to be sure.

**Comment by johanmattssonm** [comment]
Thank you for releasing the sources for your font.

I haven't thought much about this probelm but I will do some testing with a
few programs.

Cheers
Johan

**Comment by weeble** [comment]
I had a look at this last night. I'm still trying to set up a Ubuntu VM to build the source myself, but I think the issue is probably here in HheaTable:

https://github.com/johanmattssonm/birdfont/blob/master/libbirdfont/OpenFontFormat/HheaTable.vala#L93

It calculates `ascender` and `descender` based on `font.top_limit`, but doesn't adjust for `font.base_line`. In contrast, in GlyfData, y values are adjusted based on `font.base_line`:

https://github.com/johanmattssonm/birdfont/blob/master/libbirdfont/OpenFontFormat/GlyfData.vala#L244

If my understanding of `base_line` is correct, then it should be accounted for in both these places. If I manage to build BirdFont over the weekend I'll try out a fix.

**Comment by johanmattssonm** [comment]
Thank you! I will release a new version soon.

**Comment by johanmattssonm** [comment]
This issue has been solved in version 2.10.6. I can send you the new version if you give me your e-mail address.
Cheers
