### ISSUE TITLE
[IM] Don't add point when switching tools

### ISSUE THREAD

**Issue by digulla** [johanmattssonm/birdfont#61]
Currently, it's hard to stop the Bezier tool.

For example:
- Click the Bezier tool
- Click+Drag three times to create an open path
- Click on the "Select" tool
-> an additional point will be added. The path will now have four points instead of three.

BF should only add points when I click somewhere.

**Comment by johanmattssonm** [comment]
Thank you for your bug reports. I will fix this but you can press 'c' to stop drawing with the Beziér tool.

**Comment by johanmattssonm** [comment]
This bug has been fixed and the code will be included in the next release.

**Comment by johanmattssonm** [comment]
I believe this bug has been fixed in the latest release.
