### ISSUE TITLE
Cannot install .flatpak on Ubuntu 17.10

### ISSUE THREAD

**Issue by iget-master** [johanmattssonm/birdfont#62]
Hi,

I'm trying to install birdfont on Ubuntu 17.10 following your instructions:

> ### Installation
> flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
> flatpak install gnome org.gnome.Platform/x86_64/3.22
> flatpak install birdfont-3.6.2-free.flatpak

But it fails on the last step:

> error: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._OstreeGpgError.Code0: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)

Looks like we need to install a gpg signature of your package, but didn't found it anywhere.

**Comment by johanmattssonm** [comment]
Thank you for the report. I have signed and released a new flatpak but I don't have an installation with Ubuntu 17.10 to test this with. Can you do the testing for me? I have updated the instructions on the website with my gnupg key.

**Comment by iget-master** [comment]
@johanmattssonm It worked. Thanks for your attention!
