### ISSUE TITLE
Save/Export freeze

### ISSUE THREAD

**Issue by m-Linus** [johanmattssonm/birdfont#64]
Whenever I try to save or export, the spinner in the top right corner just keeps spinning. The save file is created in most cases, but I have to interrupt/kill Birdfont. 
This happened on Ubuntu 16.04. I installed Birdfont via apt-get.
There has been another report on this, but there is no working solution.

**Comment by johanmattssonm** [comment]
Thank you for the report. Which version of Birdfont are you running and have you tried the latest flatpak build?

**Comment by johanmattssonm** [comment]
I have a vague memory of fixing this a long time ago.

**Comment by m-Linus** [comment]
Version 2.14.0. I just realized that I used a very old version of Birdfont, but installing it with flatpak seems not to work for me (It says: `The Application org.birdfont.BirdFont/x86_64/master requires the runtime org.gnome.Platform/x86_64/3.22 which is not installed` )

**Comment by johanmattssonm** [comment]
Have you tried this?

flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
flatpak install gnome org.gnome.Platform/x86_64/3.22

**Comment by m-Linus** [comment]
That worked. Thanks. (Still, it's annoying that sudo apt-get install
birdfont installs an old version)

>
