### ISSUE TITLE
Help please - .fb export is impossible

### ISSUE THREAD

**Issue by Jingyi8** [johanmattssonm/birdfont#65]
Hello,

I'm really stuck. On Windows 10, I made every glyph in my new font on BirdFont, but now I can't export it. The soft run and run and run and run (CPU usage 50%) for unlimited time when I press "export button". It's bug.

Maybe someone can export it in .ttf for me? I know it is a strange place to ask this, but I can't see any other place.
Here is my file .fb file : https://drive.google.com/open?id=1xhVW4mJ9qQ0C7biVmiWnfAxYBNhUMykI
(no virus garantee !)

Thanks anyone!

**Comment by johanmattssonm** [comment]
I have found and fixed the problem. A new version with the fix will be released.

**Comment by johanmattssonm** [comment]
I can send you the exported font if you give me your e-mail address.
Cheers
Johan

**Comment by johanmattssonm** [comment]
This issue has been fixed in version 3.6.6.
