### ISSUE TITLE
I love the UI for this but it was completely unusable for me!

### ISSUE THREAD

**Issue by thedonquixotic** [johanmattssonm/birdfont#66]
I really would like to use this application but it was completely unusable for me. It ran like crap and when I moved it from my 4k laptop screen to a normal HD monitor the UI spazzed out and became completely unreadable. It's a real shame since this does have such a well designed UI.

**Comment by johanmattssonm** [comment]
Does the spazzed out UI persist if you restart the program?

**Comment by thedonquixotic** [comment]
Yes, sadly. It also runs extremely slowly, to the point that it's hard to use.
I have a surface book 2 computer so it should be adequate to run pretty much any
application. The weird thing is that it doesn't seem to be causing a spike in
CPU use when I open it. It just runs really slugglishly.

Here's a picture of what it looks like:




Sincerely,David Aslan French  
Jackalope.tech Design X Code: Pushing the boundaries of design, art, and code.
 jackalope.tech  
Find me on Facebook  Let's connect!  








On Fri, Jun 15, 2018 1:10 PM, Johan Mattsson notifications@github.com  wrote:
Does the spazzed out UI persist if you restart the program?

**Comment by thedonquixotic** [comment]
Ah dang, doesn't look like my email properly sent the image: 

![image](https://user-images.githubusercontent.com/9451726/41483398-993cf55e-709e-11e8-8aba-064bf67a9877.png)

**Comment by johanmattssonm** [comment]
Thank you!

**Comment by thedonquixotic** [comment]
I'm also def willing to pay for the program if I got it working. The project seems really cool! I never even heard of Vala before checking out the website.

**Comment by johanmattssonm** [comment]
I have tried a few things but I have not found a way to reproduce this, I don't have a HD screen. Do you have multiple screens connected to the same computer?

**Comment by thedonquixotic** [comment]
Yes. I have 2 HD screens and the laptop itself (which it launches on by default) is 4k.

**Comment by johanmattssonm** [comment]
I have not been a to reproduce this but I have made an attempt to fix it. Can you do the testing for me and attach a screenshot of the result? Here is the new version: https://birdfont.org/download/birdfont-3.8.9-free.exe

**Comment by thedonquixotic** [comment]
Closing as fixed. Thanks!
