### ISSUE TITLE
Contextual Ligatures

### ISSUE THREAD

**Issue by dvulanov** [johanmattssonm/birdfont#67]
Hello, 

Is there a way to more broadly define a contextual ligature rule?  Like beginning CANT be space (so the ligature will only appear in the middle of a word), or beginning needs to be capital?

On a side note, documentation is lacking, some tools are not intuitive (it would help SO MUCH if even just tool tips worked reliably), but what it gets right (glyph management / creation, background bitmap importing, testing) it does a great job!  Well worth the money.

**Comment by johanmattssonm** [comment]
Sadly, the TTF format does not allow for the complex ligature support you are looking for.
