### ISSUE TITLE
Mac Validation Error: 'name' table structure

### ISSUE THREAD

**Issue by dvulanov** [johanmattssonm/birdfont#68]
When I try and import a font using latest OSX (using Font Book), it reports "1 minor problem. Proceed with caution': 'name' table structure.

It gives the same error regardless if I import the regular or mac version of the ttf

**Comment by johanmattssonm** [comment]
I have fixed this problem. The fix will become available in the next release.

**Comment by johanmattssonm** [comment]
This issue has been fixed in version 3.7.1.
