### ISSUE TITLE
default/global horizontal margins

### ISSUE THREAD

**Issue by vitordino** [johanmattssonm/birdfont#69]
Hi Johan,

first of all, congratulations on your incredible piece of software.

I'm trying to design a monospaced letter, and have almost everything set up here.. my main struggle is on managing horizontal margins — or a way to create a "constant" kerning.

The vertical rulers already share a more global setting (makes sense for x-height, descendent, ascendent, etc).

I know for the majority of letters, it's not useful they share horizontal margins (each letter should have their own) but maybe a setting somewhere would set just the initial ones.

Thanks,
Vitor Dino

PS:  I've heard about vala through Elementary OS, but never really have seen it in the wild —especially on a cross plataform app — you are doing an amazing job, i'm on a mac and has a really smooth performance and intuitive interface

**Comment by johanmattssonm** [comment]
Thank you for the suggestion. Could spacing classes be a solution for you? https://birdfont.org/doku/doku.php/spacing_classes

**Comment by vitordino** [comment]
Thanks for pointing it, it will sure help me 🎉 

closing this for now.
