### ISSUE TITLE
Your curve algorithms seems to be broken, or maybe the instruction parsing

### ISSUE THREAD

**Issue by Vampire** [johanmattssonm/birdfont#70]
If you open the FiraCode Regular font and look at the zero, you will see that it does not look properly.
This is how it should look like:
![grafik](https://user-images.githubusercontent.com/325196/41949070-2a6f6c3a-79c0-11e8-8e3e-bdc8c3517f85.png)
![grafik](https://user-images.githubusercontent.com/325196/41949075-31a06946-79c0-11e8-9357-d36ae2ecf3c0.png)
This is how it looks in BirdFont:
![grafik](https://user-images.githubusercontent.com/325196/41949090-4445591c-79c0-11e8-8d77-48a64f5008db.png)
![grafik](https://user-images.githubusercontent.com/325196/41949116-5caf6164-79c0-11e8-98cb-e72171208bac.png)

**Comment by johanmattssonm** [comment]
Thank you for the report. Have you tried this with BirdFont 3.6.x?

**Comment by Vampire** [comment]
This is with latest 3.6.6, just downloaded

**Comment by johanmattssonm** [comment]
Thank you. I will try to fix it.

**Comment by Vampire** [comment]
I tested with the 3.8.12 version you posted at #32, but it is still the same.

**Comment by johanmattssonm** [comment]
I believe I have a fix for this problem. It will be included in Birdfont version 3.9.0.
