### ISSUE TITLE
Kerning Preview Issue

### ISSUE THREAD

**Issue by Daniel10106** [johanmattssonm/birdfont#71]
I have a problem with the kerning preview on Birdfont 3.7.1 version.
When I try to input a Cyrillic character into the kerning window, of course when I have already added it as a glyph from svg, it does not happen unless I type the Unicode number of the letter or select it from the Overview. It is somehow annoying to do that with every single letter, so I will be glad to see that problem fixed!

P.S. Kerning totally works with Latin characters. Also, when typing characters in Cyrillic, I use Bulgarian Phonetic keyboard setting!

**Comment by johanmattssonm** [comment]
Thank you for the report. I will try to reproduce it.

**Comment by johanmattssonm** [comment]
How do you handle keyboard bindings with a Cyrillic keyboard? Do you update all of then or do you switch between layouts? Is there an optimal solution?

**Comment by johanmattssonm** [comment]
Is there any platform in particular you want me to release for first?

**Comment by Daniel10106** [comment]
When I found this issue yesterday, I had just updated to the latest
released build of Birdfont for Windows 10.

Also, the program is quite slow, but I see that it is not only me who has
this lagging on Windows 10. Is there a possibility for the program to be
optimized for Windows 10 in the near future?


Thank You for your respond!
Have a nice day!

На 23.07.2018 г. 22:25 "Johan Mattsson" <notifications@github.com> написа:

**Comment by johanmattssonm** [comment]
I am not sure if and when BirdFont will be optimized for Windows.The problem is the performance of glib.

**Comment by Daniel10106** [comment]
I understand. At least I hope something is being planned about that!

**Comment by johanmattssonm** [comment]
Thank you for you patience. The only short term solution is to find a Mac to run BirdFont on.

**Comment by Daniel10106** [comment]
For now, I am sticking to Windows, but I am not giving up working with BirdFont because I am feeling comfortable with the interface. Good Luck with finding a solution for the issues!

**Comment by johanmattssonm** [comment]
I will probably officially release the updated version next week. Here is a file if you want to help with the testing: https://birdfont.org/download/birdfont-3.8.0-free.exe

Does it work for you?

**Comment by Daniel10106** [comment]
Hello again!
I was glad to find that the last update of BirdFont really did fix my issue with Cyrillic kerning.
A big THANK YOU for the quick answer.
I am writing about a feature that I find necessary and which is currently missing in BirdFont (please correct me if I am wrong).
When I resize my letters, how can I be sure that they will be on the exact same level? I am importing pre-done SVG capital letters, and as I imported them, I found they are quite large in the single letter edit window. So I start resizing them but in the kerning window I see or “feel” that one letter is a little bit higher or lower than the other. Is there a tutorial or something on how to compose letters correctly when working with the guidelines. Or Do I am getting the whole process the wrong way. I confess I am a novice and I am pretty excited with the clear and intuitive interface of your software so I might be missing something.

Thank you in advance,
Daniel

P.S. I can confess that the last BirdFont update somehow optimized it on my Windows which I find great! 


---
Този имейл е проверен за вируси от Avast.
https://www.avast.com/antivirus

**Comment by Daniel10106** [comment]
Here are some of the SVGs I made with Illustrator.

Изпратено от Поща за Windows 10

От: Johan Mattsson
Изпратено: 29 септември 2018 г. 23:22
До: johanmattssonm/birdfont
Як: d4nl31010cv; Author
Тема: Re: [johanmattssonm/birdfont] Kerning Preview Issue (#71)

Can you send me a few samples of you SVG files?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Този имейл е проверен за вируси от Avast.
https://www.avast.com/antivirus

**Comment by johanmattssonm** [comment]
It looks like the attachment don't made it way through. Can you send them directly to me:
johan.mattsson.m@gmail.com

**Comment by johanmattssonm** [comment]
Hi. I believe this issue has been fixed in the latest version (3.12.9): https://birdfont.org/download.php

Here is a brief description of the process:
1. Import the files (Menu->Import and export -> Import SVG folder)
2. Set the size and set the alignment to the top of your glyph:
![resize](https://user-images.githubusercontent.com/350392/46412285-5d1e1900-c71e-11e8-8e4b-8a82d83f5bda.png)

3. Move base line:
![move base line](https://user-images.githubusercontent.com/350392/46412368-a8d0c280-c71e-11e8-9c23-203ddc5f0711.png)

 4. Export a new template with and use it for future imports. (Menu->Import and export -> Export glyph as SVG)
![skarmbild fran 2018-10-03 15-00-30](https://user-images.githubusercontent.com/350392/46412460-e7ff1380-c71e-11e8-86c0-cc4f2adc2436.png)
