### ISSUE TITLE
Color fonts: SVG import should not close paths

### ISSUE THREAD

**Issue by oskay** [johanmattssonm/birdfont#72]
SVG graphics allow stroke attributes, and should not require that paths are closed.

Screenshots show file in Inkscape and file after importing to birdfont.

<img width="273" alt="screen shot 2018-10-11 at 11 30 22 am" src="https://user-images.githubusercontent.com/1009180/46825846-66743a80-cd49-11e8-8fde-52604b1bbeba.png">
<img width="1108" alt="screen shot 2018-10-11 at 11 30 09 am" src="https://user-images.githubusercontent.com/1009180/46825847-670cd100-cd49-11e8-85cf-8d9ddae103e6.png">

(Fonts with strokes like this can be used inside programs like Adobe Illustrator -- I've verified by manually editing the SVG content of OTF+SVG fonts.)

**Comment by johanmattssonm** [comment]
Thank you. Can you send me the SVG file?

**Comment by oskay** [comment]
[U+78.zip](https://github.com/johanmattssonm/birdfont/files/2470727/U%2B78.zip)

**Comment by johanmattssonm** [comment]
Thank you for your excellent bug report. I will try to fix this,

**Comment by oskay** [comment]
Perhaps not so excellent. While the SVG that I posted renders correctly in Illustrator, best practice for OTF+SVG according to the standard is to use presentation attributes rather than CSS style attributes. (for example, `fill="none" stroke="#00ff00"`, rather than `style="fill:none;stroke:#00FF00;"`).  

Making this change allows the characters (once bundled into the OTF+SVG font) to diplay properly not only in Illustrator, but also in Mac applications like Keynote.

I'm attaching updated screenshots and an updated SVG zip.

The behavior reported remains consistent, even with this change in formatting.



[U+78_MkII.zip](https://github.com/johanmattssonm/birdfont/files/2470999/U%2B78_MkII.zip)
<img width="553" alt="screen shot 2018-10-11 at 3 39 49 pm" src="https://user-images.githubusercontent.com/1009180/46838917-46a43d00-cd70-11e8-82eb-e5dca9415c96.png">
<img width="483" alt="screen shot 2018-10-11 at 3 39 17 pm" src="https://user-images.githubusercontent.com/1009180/46838918-46a43d00-cd70-11e8-8a38-1d7b66ef7cd9.png">

**Comment by johanmattssonm** [comment]
Thank you for your report. I believe a fix for this will be included in the next release of BirdFont.

**Comment by oskay** [comment]
Fantastic; thank you!

**Comment by johanmattssonm** [comment]
The closed path is not a problem in version 3.12.14 but I have not implemented round line joins yet.

**Comment by oskay** [comment]
Thank you; this update does fix the problem.
