### ISSUE TITLE
Add support for rounded join and endcap in SVG glyph import

### ISSUE THREAD

**Issue by oskay** [johanmattssonm/birdfont#73]
Following up on a footnote from issue #72:

If the input SVG file contains presentation attributes to set the stroke linejoin and linecap styles to rounded, for example in:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox=" 0 0 1000 1000"><g><path fill="none" stroke="#008888" stroke-width="40" stroke-linejoin="round" stroke-linecap="round" d="[...]
"/></g></svg>`

Then those attributes are currently ignored. 
SVG file and screenshots (Inkscape, Birdfont) attached.

Inkscape:
<img width="390" alt="screen shot 2018-10-16 at 9 12 31 am" src="https://user-images.githubusercontent.com/1009180/47030999-c5f49080-d123-11e8-912e-e0783b015352.png">

Birdfont:
<img width="446" alt="screen shot 2018-10-16 at 9 12 53 am" src="https://user-images.githubusercontent.com/1009180/47030998-c5f49080-d123-11e8-94f5-14ab7cde3bde.png">

[U+78_MkII.zip](https://github.com/johanmattssonm/birdfont/files/2483958/U%2B78_MkII.zip)

**Comment by johanmattssonm** [comment]
BirdFont 3.14.0 is released. It has support for round line joins.
