### ISSUE TITLE
flatpack installation: Segmentation fault. 

### ISSUE THREAD

**Issue by com2** [johanmattssonm/birdfont#74]
This likely is off topic but I see no other way than reporting it here. Your MantisBT account registration failed twice on me. 

After [installing flatpack](https://flatpak.org/setup/Ubuntu/) on my Linux distribution (Ubuntu 16.04 LTS) I followed the installation instruction, but the last step fails with "Segmentation fault (core dumped)". How should I proceed?

**Comment by johanmattssonm** [comment]
Hi, it sounds like it might be a bug in flatpak, I am using Ubuntu 18.04 and it seems to work but I have not tried 16.04 yet.

**Comment by johanmattssonm** [comment]
Have you tried removing the signing argument and only running
flatpak install birdfont-3.14.2-free.flatpak

**Comment by com2** [comment]
all seems to work fine. Install with sudo run without.

**Comment by com2** [comment]
Just to update that indeed the issue is only experienced with the gpg-file option
