### ISSUE TITLE
Continuous builds on Travis CI

### ISSUE THREAD

**Issue by probonopd** [johanmattssonm/birdfont#77]
Can we get this to build on Travis CI on a Ubuntu 14.04 (trusty) instance?

**Comment by probonopd** [comment]
Continuous builds are totally worth it because they immediately show if something is broken, even for pull requests you may end up getting.

**Comment by pasztorpisti** [comment]
CI is totally worth it even as a solo developer but setting it up correctly is PITA, especially when someone does it for the first time.

Even as a solo developer CI can have many advantages:

- Having consistent builds that are always performed from scratch by scripts compared to manual builds on a developer's machine where certain things (files, settings) can change accidentally.
- Being able to develop on one platform but still having builds for multiple platforms. Some of my projects were compiled to 5+ platforms (PC, consoles, mobiles) just by pushing a change from a PC.
- Being able to build/submit release binaries for multiple platforms by simply creating a tag.
