### ISSUE TITLE
Blurry on high DPI displays on windows 10

### ISSUE THREAD

**Issue by pasztorpisti** [johanmattssonm/birdfont#80]
I've downloaded the free windows version of the program (v3.21.1) and stumbled upon some easy to fix issues that can give a really bad first impression. They are display and input related but in this issue I detail only the blurriness of the whole application window.

The window of the application was really blurry on my 24" 1440p display that I'm using with 150% layout scaling. It would probably be worse on my 4K display that I'm using with 200% scaling. Fortunately this issue has two easy fixes:

# Hotfix

This is easy for the average user but most of them don't know that they have a problem and won't look for this solution, this is why the software shouldn't rely on this one.

1. Right-click birdfont.exe in explorer.
2. Properties -> Compatibility -> Change high DPI settings
3. Check the "Override high DPI scaling behavior" checkbox.
4. In the combobox (under the checkbox) select "Application"

# The right way to fix the DPI issue

While compiling birdfont.exe one of its resources is an xml manifest file that should contain an additional setting (dpiAware=true). If the executable has been compiled with the wrong manifest it can be changed after compilation with many tools (resource hackers) but the Visual Studio commandline tools have a specialised tool for this task: mt.exe (Manifest Tool). Using mt.exe I've replaced the original manifest with a new one that contains the `dpiAware=true` setting:

**original.manifest**
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
```

**updated.manifest**
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"></requestedExecutionLevel>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
    </windowsSettings>
  </application>
</assembly>
```

**command:**
```sh
mt -manifest updated.manifest -outputresource:birdfont.exe;#1
```

It would obviously be better to compile birdfint.exe with the good manifest right away but if that isn't possible than the above update hack can do the job.

In the Visual Studio UI the dpiAware manifest setting can be changed under the project properties. Note that DPI awareness have several levels and my setting is the most basic one. There are other levels (permonitor, permonitor v2) that might be required for people with multimonitor systems when the window is dragged from one monitor to the other that has different DPI and/or scale settings but handling those cases might require additional tweaking in the program (like handling the `WM_DPICHANGED` window message). Since this program renders its own UI it might be easier to adjust the code for those scenarios.

Windows renders the window of a dpi-unaware application onto a small surface (as if the windows scaling was a normal 100%) and then upscales the result according to the actual scale setting of windows (150% in my case).

# Screenshots

**dpiAware = false (original)**
<img width="386" alt="birdfont_not_dpi_aware" src="https://user-images.githubusercontent.com/1058990/52178573-57b60580-27c8-11e9-82a9-f3aa94c69b03.png">

**dpiAware = true**
<img width="386" alt="birdfont_dpi_aware" src="https://user-images.githubusercontent.com/1058990/52178577-64d2f480-27c8-11e9-9fba-cc3c07f0e107.png">

**Comment by johanmattssonm** [comment]
Thank you for all the bug reports you have filed. I will unfortunately be coding on other things for a couple of days but I will try to find time to fix the problems you reported some time later the upcoming week.
Cheers

**Comment by pasztorpisti** [comment]
Thank you but it isn't urgent for me. Have fun at a normal pace.

**Comment by pasztorpisti** [comment]
You are welcome.

v3.21.3 works as expected.
