### ISSUE TITLE
The tab bar doesn't update/redraw after resizing the window

### ISSUE THREAD

**Issue by pasztorpisti** [johanmattssonm/birdfont#82]
After resizing the window (regardless whether to a smaller or larger width) the tab bar doesn't update until moving the cursor over it. Windows 10, birdfont 3.21.1.

<img width="375" alt="birdfont_resize_tab" src="https://user-images.githubusercontent.com/1058990/52179268-eb3f0480-27cf-11e9-9c52-3d75626c6270.png">

**Comment by johanmattssonm** [comment]
Thank you for the report. This issue will be fixed in the next release.

**Comment by pasztorpisti** [comment]
Seems good in 3.22.1. Thanks for the fix.

**Comment by johanmattssonm** [comment]
Thank you for the testing.
