### ISSUE TITLE
The ESC key should cancel editing instead of typing a seemingly whitespace character into the editbox

### ISSUE THREAD

**Issue by pasztorpisti** [johanmattssonm/birdfont#83]
On the ligatures tab clicking an editable item shows an editbox (under the tabs) and a "SET" button on its right side. The keyboard focus is in the editbox until pressing ENTER or the "SET" button with mouse.

Currently pressing ESC inserts a character into the editbox that is rendered as a relatively wide whitespace.

Pressing ESC should either do nothing or should cancel the editing operation (and possibly use the original unedited value).

Windows 10. Birdfont 3.21.1

**Comment by johanmattssonm** [comment]
Thank you for the report. A fix will be available in the next release.
