### ISSUE TITLE
Site repository is broken/outdated

### ISSUE THREAD

**Issue by QuLogic** [johanmattssonm/birdfont#86]
On https://birdfont.org/ the "Git repository" link points to [this gitphp](https://birdfont.org/gitphp-glip/index.php?p=birdfont.git&a=summary), but it doesn't seem to have been updated in 2 years. The "Recent Changes to the Source Code" at the end of the page also points to commits that are 2 years old (because it's the same gitphp site.)

As there are no dates in the Release notes or Downloads, this gives the impression that Birdfont is dead, when it is still actively being developed.

**Comment by johanmattssonm** [comment]
Thank you for the report. I have updated the repo.
