### ISSUE TITLE
Cannot open ttf from folder with accents

### ISSUE THREAD

**Issue by danieltuzes** [johanmattssonm/birdfont#87]
I cannot open an existing font if the container folder has accents in it. If the folder name is "[Új mappa](https://translate.google.com/#view=home&op=translate&sl=hu&tl=en&text=%C3%BAj%20mappa)", then I cannot open the font: the program opens but starts a new font.

**Comment by johanmattssonm** [comment]
Hi. Thank you for the report. Which OS are you using?

**Comment by danieltuzes** [comment]
Windows 10.

**Comment by johanmattssonm** [comment]
Hi. I tried to reproduce this on Windows 10 but I have not managed to get the same result as you got. Do you get any error messages? Have you enabled folder protection in Windows? Can you send me a log file of what happens when you try to open the font? You can enable logging in the settings tab.
Cheers

**Comment by danieltuzes** [comment]
No, I don't get any error messages. I can only confirm that accents are the problem: Ú, ú, ü, first place, middle place... etc
[birdfont_2019-05-21T21_15_08+0200.log](https://github.com/johanmattssonm/birdfont/files/3204081/birdfont_2019-05-21T21_15_08%2B0200.log)

**Comment by johanmattssonm** [comment]
Hi. Thank you for the log file. I can conclude that the error occurs somewhere in the freetype library. The error code is 0x01, Cannot_Open_Resource. I have not seen this before and it might be something with this particular font. Does other fonts in that folder open correctly? Can you send me the TTF file in question? It is OK to send it via e-mail if you don't want to make it public.

**Comment by danieltuzes** [comment]
I tried with fonts CMU Sans Serif and DejaVu Sans, both are free. With DejaVu Sans I get the following error message.

[accented_folder.zip](https://github.com/johanmattssonm/birdfont/files/3204197/accented_folder.zip)
[birdfont_2019-05-21T21_42_26+0200.log](https://github.com/johanmattssonm/birdfont/files/3204198/birdfont_2019-05-21T21_42_26%2B0200.log)

**Comment by danieltuzes** [comment]
The previous errors were found on Win 10 Hungarian edition, but on English it is the same.
[birdfont_2019-05-21T21_52_27+0200.log](https://github.com/johanmattssonm/birdfont/files/3204251/birdfont_2019-05-21T21_52_27%2B0200.log)

**Comment by johanmattssonm** [comment]
Thank you. I have managed to reproduce this problem now but I will probably turn to the freetype project in order to get this problem fixed in the upstream library, it might take a while.

**Comment by johanmattssonm** [comment]
Hi. I believe this problem has been fixed in version 3.24.2. Can you test it for me?
https://birdfont.org/download/birdfont-3.24.2-free.exe

Please backup your font first.
Cheers
