### ISSUE TITLE
Center glyph vertically

### ISSUE THREAD

**Issue by andidev** [johanmattssonm/birdfont#88]
There is a way to center glyph horizontally but not vertically. This is pretty handy when working with icon fonts where you want all icons to be horizontally and vertically centered. Is there a way to do this or is this a feature request?

**Comment by johanmattssonm** [comment]
I have not implemented that, yet. A custom horizontally centered guide helps.

**Comment by johanmattssonm** [comment]
A problem might be defining what horizontally centered means. Is it in the middle between baseline and cap height or is it between the bottom margin and top margin? More combinations exists. Do you have an opinion on this?

**Comment by andidev** [comment]
As I can see it there seems to be a defacto standard (for font icons):
1. The height of the icons is set to "top_limit" - "bottom_limit" = 100
2. The icons seems to be centered between "top_limit" and "bottom_limit"

So I would say center it between "top_limit" and "bottom_limit"


## Limits/guides used for fonts
### Ionicons
```xml
<horizontal>
	<top_limit>87.5000000000</top_limit>
	<top_position>66.6015620000</top_position>
	<x-height>66.6015620000</x-height>
	<base_line>0.0000000000</base_line>
	<bottom_position>0.0000000000</bottom_position>
	<bottom_limit>-12.5000000000</bottom_limit>
	<line_gap>8.9843750000</line_gap>
</horizontal>
```

### FontAwesome
```xml
<horizontal>
	<top_limit>85.7142860000</top_limit>
	<top_position>85.7142860000</top_position>
	<x-height>85.7142860000</x-height>
	<base_line>0.0000000000</base_line>
	<bottom_position>0.0000000000</bottom_position>
	<bottom_limit>-14.2857140000</bottom_limit>
	<line_gap>0.0000000000</line_gap>
</horizontal>
```

### Material Design Icons
```xml
<horizontal>
	<top_limit>100.0000000000</top_limit>
	<top_position>66.6015620000</top_position>
	<x-height>0.0000000000</x-height>
	<base_line>0.0000000000</base_line>
	<bottom_position>0.0000000000</bottom_position>
	<bottom_limit>0.0000000000</bottom_limit>
	<line_gap>0.0000000000</line_gap>
</horizontal>
```

**Comment by johanmattssonm** [comment]
Thank you for the research. I will implement that. Which OS are you using?

**Comment by johanmattssonm** [comment]
I have implemented this. It will be apart in the next release.
Cheers

**Comment by andidev** [comment]
I'm using Mac latest osx

**Comment by johanmattssonm** [comment]
Thank you. I am not at home and did not bring my Mac. It will take a few weeks until I can release this for Mac.

**Comment by andidev** [comment]
No problem. Thanks for the quick reply! Awesome work!

**Comment by johanmattssonm** [comment]
Hi. I have released a version with a possible fix for a Windows issue and the code contains this fix as well. Here is the release in case you want to test it on Windows:
https://birdfont.org/download/birdfont-3.24.3-free.exe

The Mac version will be released later.

**Comment by johanmattssonm** [comment]
The mac version has been released.
