### ISSUE TITLE
Decimal floating point decimal issue

### ISSUE THREAD

**Issue by andidev** [johanmattssonm/birdfont#89]
For example 
- Saving a stroke width of 3.4 
<img width="415" alt="Skärmavbild 2019-06-17 kl  10 08 12" src="https://user-images.githubusercontent.com/571389/59588838-d14fef80-90e8-11e9-892c-ad4646fd943d.png">

- Save file and close it

- Reopen file and now the width of stroke is 3.39 (stroke="3.3999999999999999" in .bf file)
<img width="399" alt="Skärmavbild 2019-06-17 kl  10 12 58" src="https://user-images.githubusercontent.com/571389/59588852-d7de6700-90e8-11e9-9959-f3e2f3763789.png">

**Comment by johanmattssonm** [comment]
Thank you for the report. A fix will be included in the next release.

**Comment by johanmattssonm** [comment]
Hi. I did discover a new bug when a fixed this one. Stroked paths has too many points after export. It will also be fixed in the next release.
