### ISSUE TITLE
Vertical guides

### ISSUE THREAD

**Issue by andidev** [johanmattssonm/birdfont#90]
Is it possible to create vertical guides? Would be great for icon creations.

**Comment by johanmattssonm** [comment]
Not yet but I might add it in future releases. Should the guides be same in
all glyphs?

>

**Comment by andidev** [comment]
Yes that would be really nice! Then it is easier to keep similar widths of the icons.

**Comment by johanmattssonm** [comment]
The next version of Birdfont will have support for custom vertical guides.

**Comment by johanmattssonm** [comment]
Hi. This feature is included in version 3.30.0.
