### ISSUE TITLE
Birdfont not opening

### ISSUE THREAD

**Issue by ChristopherSchubert** [johanmattssonm/birdfont#92]
Same issue as reported here:  https://birdfont.org/bugtracker/view.php?id=146

I was able to resolve it by editing the appdata settings file.  The values for "window_x" and "window_y" were both set to -32000.  Resetting to 0 resolved the issue.

**Comment by johanmattssonm** [comment]
Thank you for the report. I might just make it impossible to put the window that far of the screen but it would be even better if someone knows how to reproduce the problem.
Cheers.

**Comment by johanmattssonm** [comment]
Could it be the case that the program was moved to another screen?

**Comment by johanmattssonm** [comment]
I have found out that this happens if the size and position of a window is stored while the program i minimized. I will include a fix for the in upcoming version. Thank you for providing the details!

**Comment by johanmattssonm** [comment]
Hi. I believe this issue has been fixed in the latest release. Please let me know if it happens again.
