### ISSUE TITLE
Escaped unicode is skipped while importing svg

### ISSUE THREAD

**Issue by thoka** [johanmattssonm/birdfont#94]
Entries with escaped unicode names like `<glyph unicode="&amp;" glyph-name="ampersand" ...`  are ignored when I open a svg font (see for example [the single stroke hershey fonts provided by the hershey-text inkscape extension](https://gitlab.com/oskay/hershey-text/-/tree/master/hershey-text%2Fsvg_fonts).

**Comment by johanmattssonm** [comment]
thank you for the report.

**Comment by johanmattssonm** [comment]
A fix for this issue will be included in the next release.
