### ISSUE TITLE
Capital letters ligatures don't work

### ISSUE THREAD

**Issue by siftra** [johanmattssonm/birdfont#96]
Ligatures for capital letters don't seem to work. I have attached a Birdfont file with the capital letter "T" and a "TT" ligature that shows this behavior.
[Dummy_font.zip](https://github.com/johanmattssonm/birdfont/files/4496161/Dummy_font.zip)

**Comment by johanmattssonm** [comment]
The source glyphs should be separated by space. Please let me know if this still is a problem.

**Comment by siftra** [comment]
Oh, I forgot about adding spaces! Sorry to waste your time and thank you for responding.
